### ISSUE TITLE
Space in member name breaks search on Lane

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#1009]
* Version of CORE?
2.2 (-ish)

* Issue with Lane

* a bug report
So what appears to be happening, is that the space in their name breaks the search by name, and no search for first name or last name characters will yield any result for a member with a space at the start of the name.

**Comment by gohanman** [comment]
So the basic issue here is we're doing a prefix match instead of a general one (i.e., `LastName LIKE 'JOHN%'` rather than `LastName LIKE '%JOHN%'`). I think we can't **just** change the search query because that will be a large change in user-facing behavior. But filtering separately on the result side should fix this whitespace situation without changing how search seems to work generally.

**Comment by gohanman** [comment]
Fixed as of 2.10
