### ISSUE TITLE
Support for NCG Core Sets pricing?

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#1156]
* Version of CORE? Current

* Issue with Office, Lane, or both? Office

* Is this [mostly] a bug report, feature request, or question? Question

Is there support in CORE, now or in the works, for NCG Core Sets pricing? It is described as temporary wholesale price changes that are not sales and revert to the previous price at a fixed date.  It is mentioned in the Feb 2021 issue of _NCG Programs Update_ but not with any implementation detail,  I first heard about it about four months ago. I don't know a lot about it other than that but can probably find out more.  The store does not want sale-type messaging visible to customers.

**Comment by gohanman** [comment]
It's not really sets-specific, but we use the existing [EDLP tools](https://github.com/CORE-POS/IS4C/tree/master/fannie/batches/CAP) for this.

The upload page creates pricing rules based a spreadsheet and [optionally] assigns them a review date. The batch tool creates price change batches based on the previously created rules (to apply the Sets pricing, in this case).

On the other end of the process, we use the rules' review date as a reference for when to delete the rules, at which point the items revert into our normal cycle of updating pricing to margin. We don't bother reverting to the original pricing since a bunch would just change again within a week or two. But it'd be possible to do something similar to the page the creates the batches applying the pricing to create another set of batches reverting it. The second set would just have to be created before the first set are run.
