### ISSUE TITLE
Fannie "phones home" to improve development and support

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#370]
This is a spin-off of the thread on cron/task error-reporting #369  I'm in support of simplifying error reporting/output.  I like everything being said there.

To toss something new into the mix:  I'd be interested in pursuing some performance-related reporting for development/support purposes.  e.g. Fannie phoning home periodically, reporting errors and performance stats to a central server that we can start to use to improve the software.  This could be opt-out, of course.  But by default it should be active.
Some possible data points:
- cron task failures
- basic server performance stats
- CPU/RAM usage
- disk space available
- lane health (interpret that anyway you see fit)
- certain logfile tails

I could even imagine this being in the form of an email that gets sent nightly containing usage stats, errors, etc.  But the more advanced version probably is an encrypted remote DB INSERT.
I would be willing to provide the central server, certificates, encryption, email account, etc.

**Comment by gohanman** [comment]
Commence resurrection. I've done some work on this. It's currently structured as an emailed report.
https://github.com/CORE-POS/IS4C/tree/master/fannie/modules/plugins2.0/ReportMetrics

From the original list, I've done:
* Disk space available
* Log tails on fannie.log and debug_fannie.log
* Lane health interpreted as:
  * Server can connect to lane MySQL instance
  * Number of records in dlog from each lane

I also added:
* Total backend pages served
* Number of unique users
* Number of unique IPs
* Top 10 most-visited pages

One aspect of using email that I like is it's very transparent. Anyone can CC themselves to see exactly what information is being reported.

Some of the other ideas may wind up being platform specific and/or bump into limits of what CORE can access since it isn't root. Platform-specific probably isn't a big deal since Windows backends don't exist but anything distro-specific merits flexible configuration.

**Comment by gohanman** [comment]
Added a couple more snapshot-y numbers about products, custdata, and archived transaction data.
934d7665dbc42b4223ef0987673f9e9d978840e4

**Comment by gohanman** [comment]
Re-factoring this in #656 although some pieces of `ReportMetrics` will likely get converted into a monitor.
