### ISSUE TITLE
CoreWarehouse vs trans_archive.sum*

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#432]
Can you say a bit about where the CoreWarehouse plugin approach is at historically vs the trans_archive.sum* tables?

At the moment:
* trans_archive.sum* tables seem almost identical to the CoreWarehouse ones except for the latter's date being an integer vs a date in the former.
* The TransArchiveTask maintains trans_archive.sum* but there's no switch to not do it if CoreWarehouse is enabled.
* There doesn't seem to be a Task in the plugin for updating CoreWarehouse's tables
* $FANNIE/reports/ZipCodeReport needs the CoreWarehouse plugin and doesn't fail gracefully if it isn't enabled; would seem to belong in the plugin in this case.

**Comment by gohanman** [comment]
Sure!

The trans_archive.sum* tables were dropped here in favor of CoreWarehouse here: c56e3d8418346f6d542d4e4e40067a011d03c42d

As you note, they're basically the same anyway. The trans_archive summary tables weren't actually being used anywhere. Having both seemed like overkill. The reasons I went this direction are:
* Integer is probably *slightly* more portable than Date (as opposed to Datetime) and may index a little better
* Having these relatively unimportant tables mixed into TransArchiveTask creates extra potential points of failure in an important job
* The warehouse plugin has more robust tools for rebuilding the summary tables from older archived data as opposed to just adding the current day's data.

The CoreWarehouse plugin doesn't have a Task because the task system didn't exist yet when it was written. It probably should, now. 15b95b9322c12430cc8b104d25180f09eb00da00

As far as I can tell, the zip code report has always had the requirement. I'm not sure where it belongs; reporting based on purchases requires the plugin but reporting based on join date works without the plugin. At the very least it could adjust the options based on what data is available.

**Comment by gohanman** [comment]
Updated zip code report only displays options available w/ current config:
eaee635555fbe618f4e337bb5c6189aefbc9a90a
