### ISSUE TITLE
2015-01-16 Agenda & Minutes

### ISSUE THREAD

**Issue by jdpurdyvi** [CORE-POS/IS4C#435]
Kinda a false post. Several people will not be able to make it for this week's call, so the call will most likely not be happening.

I hope to have a walkthrough of the Wedge's multistore backend environment for the call 2015-01-23.

thanks!

**Comment by gohanman** [comment]
Thanks John.

#433 & #434 reflect most of the progress on topics from last week. Configuration abstraction is done on the lane side and posDevelop *will* yank things out of ini.php once they're stored in opdata.parameters. I haven't had a chance to put it into production testing yet. Fannie needs more work. There's going to be some overlap between the logging+dashboard idea and the configuration abstraction. Any problems caused by changes to configuration management need to ripple up into the dashboard and/or fire off alerts.
