### ISSUE TITLE
GeneralDayReport departments now vs. then

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#461]
Add reporting option to GDR to choose department mappings at "time of sale", or "now"

**Comment by gohanman** [comment]
I would rather get rid of this in the few places where it exists than add it in more places. It inherently results in more complicated queries, runs slower, and doesn't completely mean what it says.

Accounting for items that existed at "time of sale" but don't exist "now" is messy. I'm leery of making this a standard, expected feature on reports. Writing every reporting query twice isn't a trivial undertaking, and it means extra steps on each future report, too.

**Comment by joelbrock** [comment]
that makes a lot of sense to me.
In the cases where department assignments have changed, would you then
recommend "massaging" historical data to match up to current dept.
assignments?

**Comment by gohanman** [comment]
I don't think changing historical data is ever a good idea. You can't
"unchange" it, so there's no way to review what originally happened.

I don't have a recommendation per se; IMO there is no good way to
accommodate this request on a broad, all-reports scale. Mucking with
historical records is bad, writing two queries per report is bad, and
imposing additional data integrity rules that allow clean single queries
but break compatibility with existing installs is bad.

**Comment by gohanman** [comment]
I should probably expand on my cynicism a little.

Say we want per-department sales based on current settings. The query's going to look something like this:
```sql
SELECT
    CASE WHEN e.dept_no IS NULL THEN d.dept_no ELSE e.dept_no END as dept_no,
    CASE WHEN e.dept_name IS NULL THEN d.dept_name ELSE e.dept_name END as dept_name,
    SUM(total) AS total
FROM trans_archive.dlogBig AS t
    LEFT JOIN products AS p ON t.upc=p.upc
    LEFT JOIN departments AS d ON t.department=d.dept_no
    LEFT JOIN departments AS e ON p.department=e.dept_no
WHERE t.trans_type IN ('I', 'D')
GROUP BY
    CASE WHEN e.dept_no IS NULL THEN d.dept_no ELSE e.dept_no END,
    CASE WHEN e.dept_name IS NULL THEN d.dept_name ELSE e.dept_name END
```
We have to join on departments twice because we have to account for open rings as well as because any UPC that exists in dlog but not in products won't have a "current" setting. Throw in a super department setting or add a WHERE clause applying to department number and the logic gets more tortured to juggle two sets of departments. I don't see any practical way to generically transform a query that operates on dlog.department (i.e., at time of sale) into something like the above. There's too much complexity so it results in writing two separate queries.

I was originally thinking this could be cleaned up by forbidding product deletes so any item record in dlog always has a corresponding record in products, but that still doesn't account for open rings.

This may fit better in the core_warehouse plugin where the transaction data has already been aggregated in useful ways and queries can be structured differently. If that's the case, it would probably be good to have a standardized way for the two to interact. If the plugin is enabled and the default report supports it, the user gets an option to select data source (standard or warehouse) and possibly some additional options like current vs. time of sale depending on the data source. Ideally, I don't think it would be necessary to rewrite entire reports. The standard report could just offload fetch_report_data() method to but still handle most of the UI and report rendering.

**Comment by gohanman** [comment]
Proof-of-concept, albeit not this specific use case:
130a0ed841d430dbe8d2e1e02a600dc517789ac9

If we go this route, I have some documentation to write, but in essence:
* CoreWarehouse provides a set of "Data Source" classes
* Each Data Source declared which report(s) it's compatible with
* If the plugin is enabled, FannieReportPage:
  * Prepends a data source choice and any additional fields to the report's initial ```<form>```
  * Retrieves report data via the Data Source if requested

I used the Zip Code report as a test case since it already relied on the warehouse plugin.

**Comment by joelbrock** [comment]
Interesting....  I dont know how CRITICAL it is that this be an available feature.

But certainly it is one that would be valuable to NEWer stores or stores just getting started in POS and still working on establishing their item file / dept. structure.

**Comment by joelbrock** [comment]
I'm happy to let it lie, knowing that we have the tools in place (thanks @gohanman ) to build it out further in the future if need be.

**Comment by gohanman** [comment]
I can certainly see the value of it if the department structure isn't stable. And it makes sense that would be the case with newer stores. It's an odd situation where a simple and straightforward request is surprisingly complicated under the hood.

This may overlap some with #453. Running reports against raw transaction data may just be awkward or slow in certain situations. Making use of pre-populated summary tables is a lot easier than having Fannie create temporary ones dynamically.
