### ISSUE TITLE
Using old nav in the interim

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#463]
I've upgraded Fannie and the old-style nav fails in `FanniePage`s that have not been coded for the theme (or I assume that's the problem).  Many sets of this each time and the menu doesn't display.
```
Undefined index: url Line 29, /var/www/IS4C/fannie/src/navbar.dynamic.php
Undefined index: url Line 50, /var/www/IS4C/fannie/src/navbar.dynamic.php
Undefined index: label Line 50, /var/www/IS4C/fannie/src/navbar.dynamic.php
```
```php
// line 29
if(strlen($entry['url']) != 0 && substr($entry['url'],0,1) != '/'
// line 50
printf('<a href="%s">%s</a>',$entry['url'],$entry['label']);
```
Any way to still use the old until I can get to whatever is involved in the `$themed = 1` coding?
Or maybe "What is the minimum to get themed?"

**Comment by gohanman** [comment]
I can definitively say "maybe"!.

The main hangup is that both menus are using the same $FANNIE_MENU setting but expect a different array structure. 

This (c3e64c9e358a5eac65021f3041b2bce4c2efe940) will convert the new menu setting to something resembling the old menu setting. However, each menu entry will simply have a list of links;  there's no "depth" with nested flyouts. But having identical menus regardless of left/top positioning is probably a plus.

The other option if you want the nested menus is disabling $FANNIE_DYNAMIC_MENU. This won't effect the new menu at all since it's always editable, but the old menus will revert to the old default with multiple tiers. I'm guessing two slightly (or very) different menus is not desirable, but it is another option.

As far as updating old-style pages, [this](https://github.com/CORE-POS/IS4C/wiki/Tips-for-Bootstrap) is what I have for documentation right now. Simply setting $themed=true may be OK in some cases. ```<tables>```s are probably the only thing that demand immediate attention. Form fields with squared corners instead of rounded may be a lower priority. Questions on Bootstrap and/or edits to the wiki page are definitely good. Expanding the set of tips (or editing my gibberish to be more understandable) would be helpful for all developers.
