### ISSUE TITLE
Agenda Idea for 2015-03-20 - Phasing out "Fannie": $backendName or "NewName" ?

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#471]
Given the recent interest of a coop in Ireland, where this name means something different than in America, and that there is even a bit of similar sensitivity among some people in Canada, could we talk about:
- calling, or 
- giving the option to call

IS4C-CORE's backend something else, especially in public?

Labels, system component names (files, classes, vars), documentation and what we are used to calling it are facets that would be addressed in different ways.

I initially liked the `$backendName` or `gettext("Back End")` (also `_("Back End")`) approach, but the term is so pervasive and so potentially off-putting in some cultures I wonder if a new name is not really needed.  And a good one has not occurred to me.

**Comment by gohanman** [comment]
Re-name-ability: d996467096d56b01c5d768f2bebef8df24256bd9

I think there are essentially three potentials tiers to this:
1. Making the name editable
2. Changing the default name including the name that appears in documentation, issues, discussions, etc
3. Replacing the name internally in code

I think that's more or less in order of difficulty and priority, too.

**Comment by joelbrock** [comment]
i support this move but also do not see it as an urgent need.  Esp. with the existing re-name-ability options.
Building in some simple GUI tools to allow for upload + cropping of a store logo, as well as the existing custom naming of Fannie makes it highly customizable.  Individual stores can come up with clever, cute, or boring names.  I know a couple co-ops i have worked with refer to Fannie as "her" or "she" in an anthropomorphized sense.  Like she was a co-worker of theirs.... Which i thought was fun, and so did they.

possibilities:

|frontend|backend|
|----|----|
|CORE|CARE (**C**omputerized **A**dministrative **R**etail **E**nvironment)|
|POS|CORE|
|CORE-Ops|CORE-Admin|
|heads|tails|
|Stem|Root|
|(other|dualities...)|

**Comment by gohanman** [comment]
I don't know if *built in* uploading and cropping is really necessary, but:
![logoed fannie](https://cloud.githubusercontent.com/assets/426966/6759778/cacbee50-cf10-11e4-87cf-0f167dbed14d.png)

To summarize the call conversation, I don't think Fannie needs to renamed in a re-branding sense. I think the components of CORE can be described in a more functional way. The software is CORE-POS, and it includes various features for various tasks. If I'm looking at a table of contents for documentation that says something like:
* CORE-POS
  * Fannie
    * Managing products
    * Managing members
    * Reporting

That "Fannie" bullet point is really just jargon. If it said something descriptive - Administration, Management, Tools, etc - that would be more informational. Rather than trying to neatly divide everything into two named components, we could simply describe the various pieces of functionality in CORE-POS.

To be honest, my favorite thing about this approach is that re-branding is something where we could debate new names forever. Just keeping the top-level brand and being descriptive about everything else is a simpler path forward.

As far as I'm concerned, stores that like the current name can keep calling it Fannie forever. The only real short-term tweaks might be:
* Changing the default, out-of-the-box name (Administration or Management or even just CORE-POS)
* Changing the directory name "fannie" to something else. Providing a symlink named "fannie" should make that transparent in most configurations. A Windows installation might break and need to be reconfigured, but I don't think any Windows-hosted backends exist in production environments.

**Comment by flathat** [comment]
Two of the interesting things that came out in this discussion (from a small sample of systems) were:
- the naming of things varies a lot, can depend on history (the development of the system over time), structure, and use/functionality.  The current name is then mostly historical, doesn't represent a scope that is dictated by necessity. The lane/back-end distinction seems strong to us but SMS, as I understood it, does not divide things that way.
- the scope of what people understand by POS varies but is generally expanding to include purchasing and inventory.

Our discussion is leaning towards function-based names.  The top-level menu of the current (1.2+) back-end is close to Andy's list above.  I think distinguishing purchasing and inventory when they are more complete would be good for indicating scope especially to people who want an overview, even though they could functionally be under "Item"/"Product".

I don't discount the value of good names but haven't heard a new one that appeals to me.  Sets like CORE-Lane, CORE-Item, CORE-Membership, etc. indicate the major functional areas under the system as a whole.
