### ISSUE TITLE
How does information get from fannie to the lane?

### ISSUE THREAD

**Issue by ericools** [CORE-POS/IS4C#474]
I am attemting to learn how this whole system works and I have figured out the actuall POS functions however the instructions for how to change things in fannie don't seem to match the actuall menu layout I see.  I have figured out (I think) how to add members, products, and so on but I don't understand how to get those changes to take place in the POS.  I have tried to "Synchronize" menu options and it says things like "Custdata table synched" but the new members are still not available in the POS.  Can anyone help me out or point me to the proper documentation?

**Comment by joelbrock** [comment]
Could be a settings mis-match between Fannie and the lane.

After a successful sync of custdata (for example) can you access the table
at opdata.custdata directly (via phpmyadmin, command-line, etc.) and see
your newly added member entries there?  If not, you may be syncing from
fannie to a database on the lane other than opdata.
Also, have you set up debug logging on Fannie?  That may be collecting some
useful troubleshooting info as well.

**Comment by gohanman** [comment]
Are you seeing the menu that looks like this?
http://core.gohanman.com/fannie/item/ItemEditorPage.php
That is newer and there may be bits of documentation that are out of date. Sorry about that. Feel free to file them as issues/bugs.

Do you get any lines like "Lane 1 (IP Address) custdata completed successfully"? If not, you need to tell Fannie where the lanes are. On the configuration page (fannie/install/) there's a section for Lanes to database IPs, usernames, passwords, etc.

I think my guess is more likely than Joel's since custdata sends by drop&re-create by default :P

This is redundant in a test/development setup where a single machine is acting as both Fannie and the lane. In a production environment there's one machine running Fannie and several *other* machines acting as lanes. Edits happen centrally on Fannie and are pushed out to the lanes for resiliency. There's one authoritative version of the membership table, for example, but each lane has its own copy and can continue to function during a local network outage.

**Comment by ericools** [comment]
Oh, thanks.  I had not added any lanes in the fannie install yet.  Once I did that sync worked.

**Comment by ericools** [comment]
Alright, follow up.  How do I get the sales to show up in fannie?  There doesn't seem to be a sync option for sales.  The todays sales report shows no sales after I ring things up.

**Comment by gohanman** [comment]
Sales sync should be automatic with the caveat that transactions under the training cashier (log in w/ 9999) are excluded from reporting. If you see records in core_trans.dtransactions on Fannie, syncing is happening.

If not, there's a Server database section on the lane configuration (pos/is4c-nf/install/) that needs to be pointed at Fannie's database. Data transfer is "push" in both directions.

**Comment by ericools** [comment]
Ah, apparently it defaults as register 99.  I changed it to 1 and now it seems to work just fine.

**Comment by gohanman** [comment]
Yep, forgot to mention that. Lane 99 is the designated testing lane and
Employee 9999 is the designated training login.

**Comment by flathat** [comment]
There is an open Webex session every Friday at 11am CT for discussing all things CORE that you are welcome to join:
https://ncga.webex.com/ncga/j.php?J=805161119
You can also join by phone, alone or as audio link to the above:
Call-in toll-free number (US/Canada): 1-866-469-3239
Access code:805 161 119
Sometimes Agenda suggestions are posted as issues in this queue but you can always show up with whatever is on your mind.
Thanks to NCGA for supporting this valuable service.

**Comment by gohanman** [comment]
I added some contextual info on the configuration screen if lane 99 is chosen:
52cd7054d2f09303cf88beffdf54fcb1bdb76114
and a wiki section on architecture addressing some of the cross-over involved in linking different components together once each component is installed.

**Comment by gohanman** [comment]
I think this is effectively addressed.
