### ISSUE TITLE
Paycard Plugin setup Documentation.

### ISSUE THREAD

**Issue by roberski** [CORE-POS/IS4C#480]
Hello,
I've finally got permission to start testing integrated credit cards with FirstData but I've been running in to some hard/software issues. I think they may just be config issues.

I'm using IDTech Sign & Pay terminals. If I run the driver in the verbosely it seems to be working fine, I can scan cards and it will show the read. However it doesn't seem to be changing state at all, either from customer interaction or via message from CORE.

![screenshot from 2015-03-27 15 54 01](https://cloud.githubusercontent.com/assets/3090402/6875994/d56a566a-d499-11e4-8cd9-96e7da7150ad.png)

I've both direct input and messaging, but IS4C never seems to use the terminal data, when I do a credit card (CC) tender it sends a rePoll and a termReset. After the termReset the window goes from saying "Swipe Card" to  being blank.

There doesn't seem to be vary much in the documentation about the the actual hardware setup.
I know that in the past I've had it running so that when I used a credit card tender it would ask if I wanted to charge the customers card.

I guess my questions are:
Is there another command I should use for integrated tenders?
Am I missing some settings?
What should the transaction flow look like?
Are there people using the Ingenico terminals in production yet? (and what are people using?)

Thanks,

**Comment by gohanman** [comment]
You're right, there's not as much documentation as there should be.

The driver has two modes - direct and messages. I think the latter is preferable but the former persists because there's a *compile-time* setting is C# which is a pain in the neck for upgrades and remote support. The setting in question in SPH_SignAndPay_USB is a boolean named auto_state_change.
* "messages" should use auto_state_change=false. In this mode, the terminal only changes screens when directed to do so by POS. For example, POS receives a message from the terminal containing a block of encrypted card data. In response, it sends the terminal a command to display the credit/debit/ebt screen. This approach ensures POS and the driver are always on the same page in terms of what screen is shown and data sent by the terminal is acknowledged as received by POS.
* "direct" should use auto_state_change=true. In this mode, the terminal sends data to POS and immediately proceeds to the next screen. It's hope-for-the-best mode.

The command to charge the current card is "CCFROMCACHE". I don't typically use it that way. With Paycards and QuickMenus enabled, "CC" should produce this menu:
![cc menu](https://cloud.githubusercontent.com/assets/426966/6876554/99ecf366-d496-11e4-8f42-5cca859421fa.png)

Transaction flow would look like this:
* Terminal is at swipe card screen.
* Customer swipes card
* Message TERM => POS "PANCACHE:[data]"
* Message POS => TERM "termGetTypeWithFS"
  * If EBT is disabled, this would instead be "termGetType"
* Terminal displays the card type selection screen
* Customer selects type
* Message TERM => POS "TERM:[card type]"
  * Credit case
    * Message POS => TERM "termWait"
    * Terminal displays wait for cashier screen.
  * Debit/EBT case
    * Message POS => TERM "termPin"
    * Terminal displays PIN entry screen
    * Customer enters pin
    * Message TERM => POS "PINCACHE:[data]"
    * Message POS => TERM "termWait"
    * Terminal displays wait for cashier screen
* Cashier enters "CCFROMCACHE" directly or via menus
* POS formats data and submits to processor
* Processor sends back response
  * Approval case
    * Message POS => TERM "termApproved"
    * Terminal displays approved screen
    * If signature required
      * Message POS => TERM "termSig[optional caption]"
      * Terminal displays signature screen w/ caption
      * Customer signs
      * Message TERM => POS "TERMBMP[bitmap filename]"
    * Message POS => TERM "termReset"
    * Terminal returns to swipe card screen
  * Decline/Error case
    * Message POS => TERM "termReset"
    * Terminal returns to swipe card screen

In direct mode, all the POS => TERM messages prior to processing would be omitted. The post-processing ones would still be there.

2dbeec06e07073935c40f6e2915574616b194137 may be of interest. Direct interaction with USB device files in Linux has been hit and miss depending on exact hardware and distro version. Using a 3rd party library by someone who knows more than me about Linux's USB subsystem. If you're not seeing any random exceptions / crashes / half-drawn screens, great! but otherwise this might be worth trying.

I have a mostly working integration done with an Ingenico isc250. The messages between POS and the driver are identical to what's described above for ID Tech. In theory anything that runs Ingenico's RBA/Telium OS ought to be compatible. I got as far as verifying both credit and pin debit transactions against Mercury's test gateway. My isc250 has an old OS with a minor bug on the card type selection screen. I haven't got around to updating the OS for a fully functional terminal. Most of the functionality is in SPH_RBA_Common.cs with wrappers handling I/O over different ports.
* RS232 definitely works. In Windows you can use a USB terminal in RS232 mode with a special driver. Probably not a cross-platform option.
* USB kind of works. I haven't spent as much time testing it. Messages that span multiple USB packets (aka reports) may not be handled correctly.
* IP might work. I don't have an ethernet terminal to test with, but sending and receiving bytes over TCP/IP ought to be straightforward.

I may well have missed a few of your questions, but hopefully this gets us closer to being on the same page.

**Comment by roberski** [comment]
The driver is showing the read if I run it in verbose mode, but it is not writing a file to ss-output. The scale is writing output files. I'm doing more trouble shooting.  Wondering if you had any input.

Thanks,

**Comment by roberski** [comment]
I guess I'm wondering how CORE talks to the terminal. I don't see a wrapper for it or anywhere to set one so I was going under the assumption that it used the same NewMagallan.php wrapper as the scale.

Is there some other line of communication that the the terminal takes?
Is it just using ajax-poll-scale.php?

**Comment by gohanman** [comment]
It is just using NewMagellan.php and ajax-poll-scale.php.

In the above transaction flow description:
* Message POS => TERM flows over UDP. The PHP side sends UDP packet(s) to a port the pos.exe driver is listening on
* Message TERM => POS goes through the filesystem. The pos.exe driver writes a file in the ss-output directory and the PHP side picks it up via ajax-poll-scale.php and NewMagellan.php

For simple troubleshooting, I'd first close the browser window so the ss-output files persist. If the driver shows a read but doesn't create an output file, then there's a C# problem. If the driver does create an output file, there's a PHP problem. In the latter case I'd set aside the output file, manually copy/paste the content into the POS browser input to see what happens. pos/is4c-nf/test/parsingTest.php might give you a clearer picture of exactly what happens when POS receives a block of encrypted card data.

**Comment by roberski** [comment]
It's not creating a file, it is failing this if online 732 of SPH_SignAndPay_USB.php:
 if (msg.Length > 63 && msg[0] == 0x80 )

I figured that out by putting a system out in that prints msg.Length and msg[0], it fails on both for multiple cards.

Some sort of configuration issue with the pin pad?

**Comment by gohanman** [comment]
Which condition is failing? First byte != 0x80, length is shorter, or both?

The technical reference manual (http://www.idtechproducts.com/download/cat_view/98-pos-keyboards-pin-pads/446-sign-a-pay-idfa-xxxx-series/483-usbhid-idfa-series/502-manual.html) covers the magstripe reader (MSR) output formats in section 2.0 (page 48). CORE is expecting to see the "Enhanced Encryption Format" which is indicated by that 0x80 byte. That's the format expected by Mercury but may not be the same as the format expected by First Data. If you're getting the unencrypted output format, the device probably doesn't have an encryption key loaded at all. If First Data requires end-to-end encryption, you'd have to ask them what keys are required and what companies can do key injections. I've always used JR's POS with Mercury.

The Sign&Pay SDK (http://www.idtechproducts.com/download/cat_view/98-pos-keyboards-pin-pads/446-sign-a-pay-idfa-xxxx-series/483-usbhid-idfa-series/484-software.html) has some prebuilt demos that let you see output formats and some other settings. The 32-bit VC one is most useful IMO.

**Comment by roberski** [comment]
Both, I figured that was probably what was happening, I have a call with FirstData today so I can ask them. Thanks for the docs I was going though their website but hadn't found them yet.

Think that should be all I need to get it going.

Thanks Again,

**Comment by gohanman** [comment]
New documentation:
https://github.com/CORE-POS/IS4C/wiki/Hardware-Driver

NewMagellan remains one of the more black-magic components of the project. I sketched out a bit about how it interacts with POS. Plus a picture! It may be stuff you already figured out on your own, but I included a link in the other hardware-related issues so might as well here, too.

**Comment by gohanman** [comment]
I captured some more of this here:
https://github.com/CORE-POS/IS4C/wiki/Card-Terminals
