### ISSUE TITLE
Store-specific versions of item descriptions in the item editor

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#486]
We would like to return to using the main CORE item editor since so much functionality has been added to it but we still want to:
1. format `products.description` and `productUser.description` differently
2. have the item editor update `productUser` on lanes

I am wondering how best to implement the first change.
(It involves keeping plain versions of `products.description` and `productUser.description` in a dedicated, store-specific, table, and the altered versions in products and productUser, and swapping the plain versions into the item editor, and massaging them at write time.)
There are interventions in classes `BaseItemModule` and `ProdUser`. I've test-coded them.  One addition, near line 98 of BaseItemModule looks like:
```php
        if ($dbc->num_rows($r) > 0) {
            //existing item
            $rowItem = $dbc->fetch_row($r);

            /* WEFC swap in the raw value of the short and long descriptions. */
            if (true) {
                // e.g. WEFCLib::getBothDesc($upc);
                $pwt = new ProductsWEFCTorontoModel($dbc);
                $pwt->upc($upc);
                if ($pwt->load()) {
                    $rowItem['description'] = $pwt->description();
                    $rowItem['ldesc'] = $pwt->search_description();
                }
            }
```
with `if (true)` standing in for a test to call an external function rather than having all of the code in the item module.

One way that would seem to work is for that test to be for a plugin that would include the model for the table referred to and a library with the function. I thought of doing it as another item module, but the changes don't fit in that kind of package. I would like to implement this in a way that another store could do something similar but different without further change to the item module code, perhaps by naming the plugin `"{$FANNIE_COOP_ID}_descriptions"`, thus, instead of `if (true)`
`if (isset($FANNIE_PLUGIN_LIST["{$FANNIE_COOP_ID}_descriptions"]))`

The second change involves using a revised version of `updateProductAllLanes($upc)`, `updateAllLanes($upc, $tables=array('products'))`, that will update more than one lane-side table but default to `products` alone. I've tested this but haven't published it yet, although it is very similar to `item/laneUpdates_WEFC_Toronto.php`.

Is this a direction upstream you are willing for upstream to bent?  If so, how best to do it?

**Comment by gohanman** [comment]
I'm definitely willing to work this in upstream. I would like to step back a little bit and look at the goals abstractly before settling on an exact implementation. As I understand it, we want to have the following basic requirements:

* An alternate item description should exist at the lane
* The alternate item description should be included in search
* Fields for both regular and alternate descriptions should exist in the item editor

I question the decision to maintain both "plain" and "altered" versions. Juggling four separate descriptions seems excessive and it isn't transparent. I think it's ideal if the form actually shows the user what will be written *before* they click save. I can see a few different ways of approaching this depending on local preferences:
* Alternate description isn't user-editable at all but instead is assembled automatically. Some kind of replaceable module handles assembly.
* Alternate description is user-editable but a sensible default is provided. Again a replaceable module provides the default. This gets a little dicey from a UI standpoint. Ex: if the default value is regular description + unit size and the user edits the size field, is there a dynamic update to the alternate description?
* Form validation module(s). The user can edit both descriptions, but before form submission the descriptions are passed through validation to check whether they conform with store standards. Ideally a validation failure message should include a suggestion for a valid description.

A combination of these may the right answer or I may be missing a component or two. But I think this is the right general direction. Build the correct description values on the item editor form so the user can see what they're doing, then simply save the submitted values.

I would like to extract productUser from this entirely. There's a products.formatted_name field that was added largely for this purpose. Keeping both descriptions in products removes the syncing issue entirely. I also think conventions about what goes in different item-naming fields need to be tightened up. Having a complete free-for-all just means anything built on top of productUser.description can't be easily shared because someone else may be using it differently. I'd like to either designate productUser as specifically for longer text on signage, or just get rid of it entirely and make a new, sanely-named table for that purpose.

**Comment by flathat** [comment]
Since you're OK with supporting this in the main editing stream (great!) it changes what to discuss.

I hope some others join this issue, so to give more background on what we do:
![screenshot_040615_082209_pm](https://cloud.githubusercontent.com/assets/1131922/7015044/6aa55d8e-dc9b-11e4-85e7-9c6d229a8821.jpg)
`products` and `productUser` currently hold the altered versions (2nd and 4th cols), `products_WEFC_Toronto` holds the plain ones that can be edited.
The altered `products.description`, for the receipt, has the package size and unit-of-measure appended. (`size` is kept separate from unit-of-measure in at least one place.)
The altered `productUser.description`, for PV search/list at cash, is based on a hand-inverted description prefixed by `brand` and followed by size-and-unit.  The plain long description was also intended for shelf tags, which in our case have room for long descriptions; this did work at the outset but shelf tag making from CORE has not been used.

Our current editor does not display the altered versions or support hand editing them.  It assumes the person using it knows the effect of editing the two base descriptions (in fact this knowledge has been forgotten or not passed on).  Maybe displaying the current altered format would draw attention.  I don't really want to make the altered versions directly editable, although I suppose someone might and the functionality could exist and not be used here.

The characters-left counter is aware of the length of the size-and-unit:
![screenshot_040615_085002_pm](https://cloud.githubusercontent.com/assets/1131922/7015225/81292da8-dc9e-11e4-830c-9378cd20eed7.jpg)
Long Desc: is the base for `productUser.description`. Manufacturer is `brand`.

There are four versions of the description; I don't see how to get around that. In our use the desc + package could be assembled on the fly for the receipt, but maybe not worth it.  If `productUser` were made obsolete then `products` would need `description_long` (inverted in our case: "Snack Bar, Chocolate Crisp") and `description_search` ("BRAND | description_long | pkg").

The current `products.formatted_name` is limited to 30 chars. Here, anyway, that limit doesn't reflect any constraint from shelf tags. The constraint would apply for an altered description for receipts, the way we currently compose `products.description` with pkg appended. For a multi-purpose signage field I wouldn't want the package detail included.

I agree about altered `description`s being a problem for other uses that expect them to be plain.

**Comment by gohanman** [comment]
OK, thanks for clarifying. Using the names from above:

* ```wefc_desc``` seems like it should map to ```products.description```.
* ```products_desc``` should map to ```products.formatted_name```.
  * When both ```products.description``` and ```products.formatted_name``` are present, the latter appears on receipts and onscreen so it carries the same length restrictions.
  * ```products.formatted_name``` could be programmatically composed rather than directly editable.
* ```wefc_search``` could map reasonably ```productUser.description``` with the primary purpose of the field being for signage but still available for search.

I don't think ```pu_desc_for_search``` actually needs to exist. As long as the constituent fields exist the same search and display options ought to be feasible without saving a separate, 4th description. 

As an aside, the example indicates operational problems to me. This is a manufactured, packaged item. It has a barcode. Why is it entered with a PLU? This search shouldn't be happening. No matter how good the search tools are, scanning items will be faster and more accurate.

**Comment by flathat** [comment]
> I don't think `pu_desc_for_search` actually needs to exist. 

This is the value the `PV` search currently scans as a single string, `description LIKE '%foo%'`, so that would need to be redone to compose the search string in the `SELECT` or search the parts separately, but only for co-ops that wanted the PV search to include `brand`.

I assumed you would leave what is in `pu_desc_for_search` up to the co-op-specific plugin (unless default) that composes it.
Or the plugin code could compose the `SELECT CONCAT(brand, ' | ', description)`.  I would think that would be slow in an operation that needs fast response.
Or the plugin could add `brand` to a list of existing fields to be searched, with the result of appending ` OR brand LIKE '%foo%'` to the base `description LIKE '%foo%'`.  That would work in our case but the plugin-composes-search-field approach is more open to local invention.

> has a barcode. Why is it entered with a PLU?

You may recall the discussion of WEFC "order codes" of 2013, which our buyer at that time preferred to UPC's for many uses. It's one of those.

**Comment by gohanman** [comment]
Right, the search queries would need to be redone. I would be astonished if there's a measurable performance difference. I'm not following how one approach is "more open to local intervention" although perhaps I'm not getting what that phrase means. Search code that examines several fields ought to be identical to composing code that concatenates the same several fields.

I do recall the notion of order codes, but I was under the impression this dealt with small-vendor items that had no barcode. Not scanning barcoded items is generally wrong. It's not a matter of local preference; there's optimal practice and suboptimal.

**Comment by gohanman** [comment]
This may be tangential, but I forgot to bring it up earlier. Does search filtering change the use case at all? Or maybe more importantly, is anyone other than me aware of search filtering? If you search for something with a large result set - e.g., APPLE - you can type *more* letters on the search result screen to pare down the list. The backspace key works in this context, too.

Maybe it makes no difference at all, but since part of what we're talking about is search I wanted to make sure this isn't a secret feature.

**Comment by flathat** [comment]
I think the buyer's rationale for order codes as the main key for organizing his purchasing system was that they were a uniform type of key that could apply both to items that had real upc's and plu's and those that didn't and were short enough to remember and type quickly. The upc was just another attribute of the item, one that was only used at checkout. At that time and for the range of operations he was performing his system was more efficient than the tools available in CORE.

Part of the result of using order codes instead of upcs and real plus was the need for extra information in the `PV` search at cash; the enhanced search replaced paper code books that had to be re-done frequently.  The filtered search (same as autocomplete, yes?) is in item maintenance.  I think it will be welcomed when the upgrade that introduces it is installed but doubt that it alone would have led to a change from the spreadsheet to the CORE tools.

I don't have anything in mind for "local invention", it's just the idea of something not being editable when it easily could be.

**Comment by gohanman** [comment]
I was reading through this again. I think there's an easier solution that we overlooked. Namely, there's no particular reason the productUser.description on the lanes has to be the same as productUser.description on the server. That gives us four description fields to work with. I'll grant it's a bit of a hack compared to making a dedicated table (SearchAliases?) but makes the transition simpler.

* products.description contains the "Chocolate Crisp Snack Bar" style description
* products.formatted_name contains the "Chocolate Crisp Snack Bar 45g" style description
* productUser.description *on the server* contains the "Snack Bar, Chocolate Crisp" style description
* productUser.description *on the lanes* contains the "BUMBLEBAR | Snack Bar, Chocolate Crisp | 45g" style description

From a coding standpoint, we need a module during save that composes and writes a description to products.formatted_name and we need a module during sync that substitutes in the long search description for productUser.description. The upside to this approach is that both these operations can happen entirely in the background. The two descriptions that are presented to the user as editable don't need to change at all.
