### ISSUE TITLE
Applying Tax to refunded items on EBT

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#489]
From a co-op:
> A new weird thing is happening.  When we refund an EBT transaction, the POS wants the refund amount to be the amount of the subtotal with tax, not the amount of the subtotal for EBT

I took a look and it _appears_ they are correct.

Upon refunding 2 FSable items (4.99 each) the dlogs show an EBT subtotal of -9.98.  But a subtotal of -10.43 (.45¢ tax).

I cannot recreate this issue on a current CORE-POS testlane.  On my testlane the tax is forgiven when using EBT.  
Any ideas?  Was this something that has been patched in the last year or so?

**Comment by gohanman** [comment]
This maybe? 2d139c88085db112b0635037e3e2c604ea4fb243

**Comment by joelbrock** [comment]
Good find.  But no.  That code is in their production system.

**Comment by gohanman** [comment]
There's nothing else in the entire codebase that manipulates the fsEligible value. I'm curious what they mean by "POS wants to". Their exact step-by-step process might help track down the problem.

**Comment by joelbrock** [comment]
Perhaps this is what they are describing.  I got this result by 
1. ringing RF1000DP260
2. FS Subtotalling using FNTL --> Food side
3. FS Eligible amount is correct, $10 minus any taxes
4. Using 0FS to tender out
![corepos](https://cloud.githubusercontent.com/assets/52835/7420781/266f7b94-ef34-11e4-8daa-1bfa3444abae.png)


Additionally, if i try to tender out using the exact amount, by entering
-1000FS
i get this alert
![image](https://cloud.githubusercontent.com/assets/52835/7420833/aa4008ee-ef34-11e4-8fbb-9afa43242393.png)

**Comment by gohanman** [comment]
Thanks! That helps a lot.

First, their tender does not appear to be using FoodstampTender. There should be a FS Tax Exempt between the tender and change lines. This would probably be zero and wouldn't solve their problem, but for the sake of being on the same page I think this setting should match for consistent behavior/debugging.

Second, I'm pretty sure using a zero tender in this situation flat-out cannot work. The tax exemption cannot be calculated without the total EBT tender/return amount, and the correct change cannot be calculated without knowing the tax exemption. I don't see any way around this.

Third, that return tender restriction is a problem. Part of it is a code structure/design issue, but I think I can work around it with redoing the entire tender system.

Fourth, there's a bug in tax exemption calculations with negative tender totals.

So, in summary, quite the issue. Now, solutions:
5d020bd2106d3ad833dfc58adb760c1d0d65e61c

I added a somewhat unwieldily named FoodstampAmountOptionalTender. Using this with the above, typing "FS" without any amount should prompt to tender -$10. Requiring a keyed amount with EBT is probably a WFC-ism that need not be forced on everyone else. The two foodstamp related tender modules are otherwise identical. This should allow consistency enforcing eligible amounts regardless of preferences on keying vs omitting amounts.

-1000FS should also be permitted using either foodstamp tender module (and -1070FS should be an error).

The tax exemption calculation bug is fixed. 0FS may be a lost cause. It may be possible to make it behave identically to FS with no amount, but the non-zero tender amount has to be in the first record rather than the second [change] record.

**Comment by gohanman** [comment]
Fix as described included in 1.4
