### ISSUE TITLE
Techhub Webex session (Friday Call) better not on Friday?

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#494]
The "Friday Call" (11am CT), a weekly Webex session that NCGA Techhub generously supports for us, has become a fixture of the IS4C and CORE support network but some have said Friday is not a very good day for them.  How is it for you?  Would another day, or time work better?

Everyone is welcome. Sometimes there is an Agenda (posted here), which is just a suggested theme for the day, but there is always room for ad hoc questions and issues.

The particulars:
Friday, 11am CT (noon ET, 10am MT, 9am PT)
[https://ncga.webex.com/ncga/j.php?J=805161119] (https://ncga.webex.com/ncga/j.php?J=805161119)
Your first time, start 15 mins early to install the plugin.
Computer audio "phone" is supported.
You can also use phone for audio or phone independently:
Call-in toll-free number (US/Canada): 1-866-469-3239
Access code:805 161 119
If you are using regular phone with website
log in at web site to get user id before calling.

Screen-shares are increasingly a feature so using a computer may be richer.  The computer interface also shows who is talking, and has a chat channel that is often used.

**Comment by chaploeb** [comment]
Thanks for asking.  I try to attend the Core call when I can, which is almost never.  Part of this is the fact that we aren't using CORE (although I'm interested in maybe changing that someday, and hope to have more resources to devote to that goal soon).

But part of it is timing.  Having the call at noon (eastern) just sucks.  Almost any other time of day would be better for me.

I realize that we're a geographically distributed group, and that means that making the call much earlier isn't really feasible for that reason.  Later would maybe be possible, but probably not on Friday-- experience tells me scheduling anything for Friday afternoon is an exercise in frustration as people leave the office early for travel, etc.

So that would be my vote-- move the call to a different day (Mon/Tues/Wed/Thurs) and have it at 3PM Central time, which puts it in the afternoon for all four North American time zones.

|PT|MT|CT|ET|
|---|---|---|---|
|9 AM | 10 AM | 11 AM | 12 PM|
|10 AM | 11 AM | 12 PM | 1 PM|
|11 AM | 12 PM | 1 PM | 2 PM|
|12 PM | 1 PM | 2 PM | 3 PM|
|**1 PM** | **2 PM** | **3 PM** | **4 PM** |

I would be remiss if I tried to sell this as anything other than personal preference, though.

**Comment by jdpurdyvi** [comment]
It's also strictly a personal preference for me. Fridays tend to fall into any one of - scrambling to get something done, taking a long weekend, office projects, and normal work days. In that order.

So, something midweek, midafternoon, feels a bit better.

However, consistency trumps everything here. Knowing that the call is a certain time each week goes a long way.

**Comment by gohanman** [comment]
Personal preference is always a factor, but over the years (!) the people participating in the call has changed. It seems worthwhile to at least check if there's a time that could work better. I do agree with John about consistency. This sort of change in schedule would need to be fairly rare.

I can see the general appeal of "not Friday". Tuesday afternoon is regularly a conflict for me. Of the remaining choices, I'd lean towards Wednesday or Thursday. Hopefully any unexpected Monday disasters would be settled down by the afternoon, but I hesitate to risk Murphy's law.

4PM Eastern strikes me as late, although I'd certainly cede to those actually in that time zone for final say. Trying to account for the west coast better this time around, I think somewhere in the 2-4PM Eastern range is the sweet spot.

**Comment by DavidHermann** [comment]
Between 1pm and 7pm Eastern on any non-Friday is fine with me.  Don and Kelley might miss more calls, but Don says that's ok.

**Comment by gohanman** [comment]
See #527
