### ISSUE TITLE
Agenda Idea for 2015-04-03 - Terminal Integration News

### ISSUE THREAD

**Issue by jdpurdyvi** [CORE-POS/IS4C#500]
I can probably chat for a while about the different integration options that are materializing.

**Comment by gohanman** [comment]
I just ran a test transaction on a VX805 with PDCX. I have somewhat more concrete thoughts now.

When the device first boots up, the screen says "Mercury". Upon initializing PDCX, the screen changes to say "Welcome". It would be nice if there was a way to tell the device "show this text" but I don't see anything like that in the documentation.

Swiping a card at the welcome screen does absolutely nothing, so far as I can tell. Upon sending the device an authorization request, the screen changes to say "swipe or tap card for $x.xx". My test cards don't support it, but presumably this means NFC is an option. After swiping a card, the screen switches to say "Processing". Finally, an auth response comes back from Mercury and the screen returns to saying "Welcome". Again, it would be nice if there was an option to specify the text (e.g., "Approved" or "Thank You").

I think this solution can work, although I do have some concerns. The whole cashier workflow probably needs to be reconsidered and revised. The sticking points that I see are:
* It would be nice if the customer could swipe or tap their card at any point during the transaction. This may very well not be negotiable though. There's a security argument for keeping card data in device memory for minimal time.
* The cashier has to send an authorization request with amount to activate the terminal for payment. This is problematic for EBT transactions where sales tax forgiveness alters the transaction total. As it is now, EBT customers would have to tell the cashier they're using foodstamps and this draws generally undesirable extra attention to the customer's method of payment. Letting POS query what kind of card is being used probably isn't a reasonable request since that would keep card data in memory longer. If the authorization request could include an alternate amount or set a flag indicating the sales tax amount is forgivable, that would work without changing the transaction flow. Partial auths already exist, so the idea of an alternate authorization amount coming back doesn't seem far fetched. This would require work on the Datacap/Mercury side of course to handle new fields/flags.
* The cashier has to specify whether it's a credit/debit/EBT transaction. I think EMV will solve this - cashier requests an EMV transaction and the card+terminal will negotiate what to do from there - but it'll be an extra headache in the mean time. Cashiers will have to ask customers what kind of card they're using rather than having the customer choose on the terminal.
* As mentioned, the ability to display an arbitrary string on screen would be nice. This is a lower priority and makes no functional difference, but at the same time doesn't really impact security.

**Comment by jdpurdyvi** [comment]
Our news is about the same. 
* The VX805 USB driver is working in Win7, Win8, and not Win2k ;)
* The compiled demo from Mercury's github page works fine
* A lot of old direct integration code is going to be rendered useless with the PDCX approach.
* No concrete news on test server availability from Mercury
* EBT/Debit PIN keys will change
* Reaching out to Datacap representatives about acquiring a test IPTran device and/or other solutions.

**Comment by gohanman** [comment]
The NewMagellan one listens on port 9000 if you want to tinker with it as an IPTrans replacement. E.g., sending an initialization request to the driver over the network:
```php
$xml = '
<?xml version="1.0"?>
<TStream>
  <Admin>
    <MerchantID>MerchantID</MerchantID>
    <TerminalID>001</TerminalID>
    <OperatorID>9999</OperatorID>
    <TranCode>SecureDeviceInit</TranCode>
    <TranType>Setup</TranType>
    <PadType>VX805</PadType>
    <SecureDevice>VX805XPI_MERCURY_E2E</SecureDevice>
  </Admin>
</TStream>
';

$ch = curl_init('http://localhost:9000');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_FRESH_CONNECT,true);
curl_setopt($ch, CURLOPT_POSTFIELDS, $xml);

$response = curl_exec($ch);
var_dump($response);
```

I'm not 100% certain how this will work in an actual card-processing context. Since the terminal needs to collect info from the customer before getting an authorization, there could be a pretty big time gap between the request and response. Various limits may prevent PHP from keeping the connection open that long.
