### ISSUE TITLE
Windows error log output

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#506]
Seeing this on a Windows testlane.  Possibly related to some scanning slowness i'm noticing?  The error _may_ indicate that the file is actually not there, or that it's looking at the directory and not the file?...  Speculating here.

[13-May-2015 13:27:39 America/New_York] PHP Warning:  file_get_contents(../scale-drivers/drivers/NewMagellan/ss-output/1149399314) [<a href='function.file-get-contents'>function.file-get-contents</a>]: failed to open stream: Permission denied in C:\apache2\htdocs\HARVEST_CORE\pos\is4c-nf\scale-drivers\php-wrappers\NewMagellan.php on line 111

**Comment by gohanman** [comment]
I believe it's resource contention. There's some tiny slice of time between when driver writes the file to disk and when the driver releases the file handle. If POS tries to read the file during that window of time, the error crops up because the file is still in use by another process (the driver). It harmless beyond the log noise and will resolve itself in ~100 milliseconds.

This is more-or-less normal on Windows and I've never seen any noticeable performance impact. I have seen rather significant differences in MySQL performance on Windows depending on which driver PHP uses to access the database. I've generally seen better performance with mysqli than PDO. I don't know how transferable that experience is other than "try mysql/mysqli/pdo and see what happens".
