### ISSUE TITLE
Preserving sigCaptures and pairing with transaction history

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#507]
Maybe a topic for a CORE call (aka, non-urgent for the moment):

What is the process/flow for preserving signature images and matching them up with transactions from history?  
Do the lanes DO anything with the BMP files collecting in ss-output/tmp?  
Is there a process for sending these to the server?  
How  do the signatures get paired with their corresponding transactions?  The filenames are cryptic, and i dont understand what the "ticks" are in C#.

**Comment by gohanman** [comment]
Yes, there is a process, but it occasionally leaves some debris behind that I've never had time to track down.

The plan is this:
* driver writes BMP file to ss-output/tmp
* driver sends message to POS indicating a signature image is available
* POS shows cashier the image
  * If cashier presses clear to reject the image, the BMP file is deleted
  * If cashier presses enter to approve the image, the content of the BMP file is loaded into the CapturedSignature table and the BMP file is deleted.

CapturedSignature syncs after each transaction just like dtransactions. It exists solely to link signature data to transactions without have a giant BLOB column in dtransactions.

Occasionally something goofs up in the plan and leaves stray BMP files sitting in ss-output/tmp. As far as I know there's never any data loss. If POS misses the message that a signature image is available, the customer will need to sign again and the first BMP file never gets deleted. This happens rarely enough that I haven't spent much time trying to pinpoint exact causes.

"Ticks" are the number of milliseconds since the system started. There's no meaning to it beyond being a [reasonably] unique file name.
