### ISSUE TITLE
Instacart Uploader Plugin

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#510]
This came up on a recent CORE call:  the notion of having a CORE Office plugin which automatically keeps Instacart appraised of price changes.  I imagine much of the logic could be borrowed from the SPINS plugin as they would do almost exactly the same thing, ie. run a specific report and upload via FTP.

Here is the [Instacart Data Import Specifications](https://drive.google.com/file/d/0B_3X5Wl_JVyLalZBSnFSTXd0MUpEVHoybUVWZjQyTzJjRXM4/view?usp=sharing) (i am not sure if this is intended to be public or not, so instacart, let me know if i should take this link down)

I would consider this functionality non-urgent.  And maybe it get rolled into an upcoming CORE project, but seeing as they are making a lot of moves into a lot of new markets, we will probably continue to rcv. questions about this.  And it's always noce to be able to tell a potential adopter "Yeah, we support that!"

**Comment by jdpurdyvi** [comment]
I tossed this up on my sandbox repository. I know the Wedge's table structure doesn't completely match, but it might be a nice reference. https://github.com/jdpurdyvi/sandbox/blob/master/reloadProductsMultistore_Instacart.php

**Comment by gohanman** [comment]
@jdpurdyvi: I'm noticing that your column headers don't match the doc @joelbrock linked.The specific stuff that stands out:
* You're not specifying a **tax_category** (which is great since Google is revealing nothing for me about what a "CCH standard tax category" is).
* You're not making any distinction between UPC items and store-assigned PLUs like bulk (which is more convenient than the spec for lookup codes).

**Comment by gohanman** [comment]
25ae29e34c6b088f7543bb7bf811ead5241400e3

Things that are missing:
* The actual FTP upload piece
* tax_category - as mentioned, no idea what this is supposed to be.
* I'm not making any effort to distinguish produce PLUs from other PLUs. I would guess this doesn't really matter despite what the spec says.
* I'm not checking last sale dates. I'm probably going to steal the Wedge's idea and adding a last sold column directly to products with a maintenance task to update it.
* There should be an option to exclude sales. I recall Harvest mentioned this as a way of offsetting Instacart fees.

I'm not doing anything with group pricing (e.g. buy-1-get-1, 3-for-a-dollar, etc). I don't see an obvious way to provide that kind of data. I think giving the price of the first item rather than the average price of a full set makes the most sense.

**Comment by jdpurdyvi** [comment]
Ha. I coded against "Version: 1.2 (November 2014)". Not mention of "tax_category"

`3.5.
` Taxes (required) 
`  3.5.1.
`   taxable_a: “Y” for taxable or “N” for non­taxable.

**Comment by DavidHermann** [comment]
> There should be an option to exclude sales. I recall Harvest mentioned this as a way of offsetting Instacart fees.

Yes, part of Harvest's agreement with Instacart is that we upload all active items, on sale or not, with regular/offsale retails only.

**Comment by gohanman** [comment]
I'm calling this good enough until there's an actual store that needs this functionality in CORE.
