### ISSUE TITLE
Styleguide Emerging

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#512]
From a discussion elsewhere the need for/value of documenting style guidelines has become evident:
https://github.com/CORE-POS/IS4C/wiki/Office-HTML-and-CSS-Style-Guide

this is 100% @gohanman, i'm just moving the discussion to a public forum.

**Comment by gohanman** [comment]
To follow up on this a little since UI/UX is a massive topic, some of the things that spurred this discussion include:

### Form Consistency
In particular, the arrangement of inputs is all over the place. I don't think there's a one-size-fits-all solution since arrangement is occasionally functional to fit a large quantity of info on screen, but a handful of layouts that cover most common scenarios would be helpful. I like this markup a lot for a layout with two columns of inputs:
https://github.com/CORE-POS/IS4C/blob/master/fannie/item/shrink/ShrinkTool.php#L124-188

### The Ever-Present Menu
A good old issue going back nearly forever! Currently the only place the menu doesn't show up (by default) is on report results. Adding the menu onto report results causes some weirdness in how Bootstrap and tablesorter 2.0 interact. This is mostly resolved at this point. Upstream now includes a newer, Bootstrap-compatible tablesorter 2.22. The default is currently unchanged and menus are omitted from reports, but enabling the always-on menu setting automatically switches over to the newer tablesorter version. I'm fairly tempted to switch the default (or even just get rid of the setting) and make the menu always-on out of the box. I'll probably hold off for a later release though at this point.

### Buttons and Placement
The pain point here is reset buttons on forms. Clicking a reset button by accident is annoying. When forms include both a submit button and a reset button, they ought to appear in a predictable (I happen to prefer submit on the left but others may disagree) with some reasonable, defined space in between to prevent accidental clicks. The submit button also ought to be highlighted in some way. I'm leaning towards a colored border. That's partially just to avoid another setting. Since colors are customizable now, a colored button raises issues about what color the text should be given the user's chosen color.

Feel free to add your own topics for "things that belong in a style guide".

**Comment by gohanman** [comment]
I copied this conversation into the wiki article.
https://github.com/CORE-POS/IS4C/wiki/Office-HTML-and-CSS-Style-Guide
