### ISSUE TITLE
UI Improvement: Sort indicator in batchlist

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#516]
The batchlist is sortable but there is no indication of this besides a user assuming that clicking on a list header _should_ cause that to sort the list according to that header title.  And cycle through ASC and DESC as they continue to click.

Something as simple as an indicator arrow icon would accomplish this.

glyphicon up: `halflings-triangle-bottom`  and down: `halflings-triangle-top`

![sales_batches_tool](https://cloud.githubusercontent.com/assets/52835/8170648/226dd43a-1367-11e5-967d-85ba7fb4bb01.png)

**Comment by gohanman** [comment]
There's not **zero** indication; the cursor's re-styled to indicate they're clickable :stuck_out_tongue:

But yes, you're right. I do think there are a couple trickier pieces though:
* The list isn't sorted by default - or at least isn't sorted in a visible way. I think putting batches in reverse order of creation is actually a pretty useful default but there's no column to put an arrow on. We could add a batchID column, but adding a column of useless information seems like a poor approach to a UI problem.
* The arrows actually aren't all that simple to add. The tablesorter jQuery plugin is doing all the actual work, so making the arrows actually respond correctly will require digging into the internals of that plugin a bit to understand how it works.
* Sorting on this particular page is also kind of a lie. It's sorting whatever 50 rows happen to be on screen which isn't necessarily the same thing as sorting all pending/current/historical batches on that column. There's no perfect solution here; sorting paginating lists requires a compromise somewhere. The other options are reloading the page each time the user sorts to grab a different, correct set of rows from the database. The extra page loads of course make sorting feel less responsive. Or you can fake pagination by shoving the entire, unpaged table into the HTML and hide all but the currently visible page. This breaks pretty much all performance benefits of pagination since the browser engine still has to deal with all the hidden rows and page load/render times can get ridiculous.

**Comment by joelbrock** [comment]
Great.  Really helpful info.  Just wanted to flag this somewhere.  Obviously this is by no means an urgent priority.  Just a UI nicety.  So if at some point in the future we are looking more closely at UI fit+polish (as i hope to _someday_ have the time to address) then this can be re-addressed then.  ...Or not.

**Comment by gohanman** [comment]
I may have oversold the level of difficulty. The set of glyphs should be defined in an API method, but as proof of concept:

**Comment by jdpurdyvi** [comment]
I disagree that the batchID is useless. Exposing to the user a simple ID helps create specificity that is otherwise lacking. When dealing with dozens of active batches and 2~3x as many future and WSLs, it's nice to be able to reference a clear ID rather than a vague name.

Invoices, receipts, POs, etc all use IDs and not names. No need to shy away with promotional batches.

**Comment by gohanman** [comment]
I still don't love the arrow icons, but with the icon choice in FannieUI they can be easily replaced later should something better come along.
b03c6b1cdb5838b6d08c056945fcd6f306cf3856

**Comment by joelbrock** [comment]
FWIW, the sort arrows was merely a suggestion.  I readily admit that at most 49% of my ideas are not brilliant.  ;-)  If we decide later that that they are obnoxious they could certainly go away w/o causing any change to the actual functionality of the page.
