### ISSUE TITLE
Keeping blueLine Current

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#519]
Where does it make the most sense to update blueLine?  
- Automatically during custdata sync?
- Nightly as part of a cron routine?
- Upon editing a custdata record?

I've used the first 2 approaches in various customizations, but i dont see that theres anywhere that CORE is doing this "natively", outside of the Virtual Coupon and No Address Alert plugins.

Also, might be nice to allow this to be user-configurable via install GUI.  I'm imagining shortcodes, which would allow stores to alter order and formatting as they desire.
ex.
#[[CARDNO]] - [[LASTNAME]], [[FIRSTINITIAL]]. ([[MEMTYPE]])
would output:
#4453 - Smith, J. (SHAREHOLDER)

Other available shortcodes could include:  firstname, last initial, charge balance, write checks?, discount, date last equity payment made, equity investment total, etc.

but there might be another approach to this thats better.

**Comment by gohanman** [comment]
I'm doing both "upon editing" and "nightly cron", albeit via plugins in both cases. I think both usages make sense. IMO this overlaps heavily with #514 but in the meantime it may be best to subdivide the field into two pieces. To me there's an *identification* component and a *notification* component. The *identification* component is what you've laid out in the short codes. This text should always be present and can be updated upon editing. The *notification* component is more variable information that may change from day to day such as a coupon being available. Cron tasks may alter the *notification* component but should probably preserve the *identification* component unchanged.

On the more re-write-everything line of thinking, it should be possible to attach one or more notifications to an account (or a person on an account) separately from how the person is identified on screen. I'd also make a distinction between active and passive notifications - active notifications are where the cashier must press a button to acknowledge or accept the notice where as passive notifications simply appear on screen somewhere.

**Comment by gohanman** [comment]
I added a setting to the Members tab for a blueline template using shortcodes more-or-less as suggested (I include mem#, member type, first/last name, and first/last initial). MemberREST::setBlueLines() updates an account using the template and substituting in the correct values.

I think the notifications piece could build off the custReceiptMessages table concept. That's currently (card_no, message, modifier_module). Adding a display_type column to control where the message notification appears - on the receipt, in the blueLine area, in the list from a member search, etc - should provide the necessary flexibility to display member-specific messages in various ways. If I'm the only one using this table, we could replace it with a more appropriately named table without any compatibility fuss. Scheduled tasks can create notifications in the dedicated table rather than mess around with custdata.blueLine. The latter is messy if multiple tasks are trying to add notifications to blueLine. They can easily wind up overwriting each other's changes.

**Comment by joelbrock** [comment]
Very cool development.  I think this will prove to be a valuable enhancement.  Making the system that much more adaptable to all the different ways co-ops like to do things.

>If I'm the only one using this table, we could replace it with a more appropriately named table without any compatibility fuss. 

To my knowledge, none of MY co-ops are using the custReceiptMessages table

**Comment by gohanman** [comment]
Lane-side implementation for receipt & blueline notifications: 2b5c71a827aa2f519579c85e1da19b78862d8a21

I realized CoopCred may be using custReceiptMessages. I should probably pull messages from both tables (if present) and do some kind of duplicate filtering.

**Comment by gohanman** [comment]
Documentation on the notifications piece:
https://github.com/CORE-POS/IS4C/wiki/Customer-Specific-Notifications

I believe this is fully addressed now. The default blueLine format is configurable in Fannie using placeholders. Saving via the MemberREST class will always write custdata.blueLine according in the configured format. Additional bits of text can be appended to the onscreen display using notifications.

All of this is slated for the next release.
