### ISSUE TITLE
Default values for Adding items

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#521]
Is it possible to set default department values for creating a new item?  Set them to NULL / 0 and disallow form submission until this is changed?  To prevent rushed / careless staff from creating items in the wrong departments.

Currently the form defaults to the lowest superID (0) --> lowest dept_no (1).

![image](https://cloud.githubusercontent.com/assets/52835/8340929/94150566-1a76-11e5-89af-673ebacb2a53.png)

**Comment by gohanman** [comment]
Not in a straightforward way. The problem is the form **doesn't** just default to the lowest number. It actually looks for existing items with similar UPCs - specifically, matching the first 8-12 digits - and uses the existing item's department setting if it can find a match. I think this behavior is actually really useful with barcoded items. Tightening up the logic for what happens when a match isn't found is probably a good idea, but POS can guess correctly often enough that going to a simple default seems like a step backwards in functionality. Picking the most frequently used department would certainly be a better choice that zero.

Coincidentally, I'm not seeing quite identical behavior. I do get superdepartment zero on items POS can't match, but my department list is filtered to only department in supder department zero. So something else is different, too, wherever the screenshot came from.

**Comment by gohanman** [comment]
Defaulting to the most commonly used department rather than zero when POS cannot correctly infer the department from existing items:
0adf99e521f6189f584e737b1caa0bb02063c741

**Comment by gohanman** [comment]
I played around with this a bit and the required part seems problematic. The Chosen plugin, which is what provides the filter-as-you-type functionality, does not really support the HTML5 "required" attribute. Setting the default to an empty value does prevent you from submitting the form, but the UI is completely messed up since Chosen is hiding the original select and replacing it with a bunch of other ```<div>```s and CSS. Depending on the browser, the user might get a pop-up "this field is required" at some random spot on the screen or might get no indication at all why the form isn't submitting. There's a years-long unresolved issue on Chosen's repo about this. I kind of doubt it's going to get fixed.

I do think the guessing behavior alleviates a number of mistakes - if the user never touches the control at all they can't accidentally click the wrong thing. So I don't necessarily like forcing them to make a selection. I could see a case for a configurable default department rather than using most-common (then again, logically this would be the configuration most users would choose).

**Comment by gohanman** [comment]
I think this is about as fixed as it can be.
