### ISSUE TITLE
Pricemethod + Sale Batch conflicts

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#531]
Have an interesting issue that I mostly understand:

Items using a pricemethod = 6 (MoreThanQttyPM) are also in a sales batch and are not ringing up with the volume price adjustment.  Items NOT in a sales batch rcv. their volume price adjustments as expected.
Let's look at one record from products:
```sql
                   upc: 0008600300486
           description: Cabernet Sauvignon
                 brand: NULL
        formatted_name: NULL
          normal_price: 9.99
           pricemethod: 6
            groupprice: 0.10
              quantity: 6
         special_price: 7.99
    specialpricemethod: 0
     specialgroupprice: 7.99
       specialquantity: 0
         special_limit: 0
```

Notice:  pricemethod = 6 but specialpricemethod = 0.  According to SalesBatchTask.php:96 $specialpricemethod should be equal to $row['pricemethod'], but in this case it is not.
Additionally i notice that specialgroupprice == special_price, which is what SalesBatchTask says to do.  It appears that because the item itself has grouppricing enabled, when it is in a sales batch the batcher also treats the sale item as a groupprice sale item.  So i'm not entirely sure how to reconcile the 2.

The co-op would need to decide whether the grouppricing applies to sale items as well.  But then SalesBatchTask needs to be able to update the records to either allow for volume discounts on sale items, or not.

**Comment by gohanman** [comment]
The sale batch task applies sets specialpricemethod to the value specified in **batchList** - i.e., group pricing defined in the sale. The sale says the item is $7.99/ea so that's what it will be for the duration of the sale. batchList.quantity => products.specialquantity, batchList.pricemethod => specialpricemethod.

I think this is the only clean way to handle it. The sales batch defines everything about the sale pricing.

**Comment by joelbrock** [comment]
Here is what a record from batchList looks like:
```sql
mysql> select * from batchList where upc = 0008600300486\G
*************************** 1. row ***************************
     listID: 91710
        upc: 0008600300486
    batchID: 674
  salePrice: 7.99
     active: NULL
pricemethod: 0
   quantity: 0
```

So it sounds like this batch need to get a pricemethod = 6 and a quantity = 6.  But what about the groupprice?  which should be 0.10 (10% off)?  Does batchList need to have this data?  Could it be pulled from products.groupprice?

**Comment by gohanman** [comment]
In a perfect world, the batch interface (or an alternate one) would provide the user with a inputs to set the batch fields appropriately. Trying to inherit things from products may not always match what the user actually wants. Supporting this specific price method is going to require changes to the batchList structure and task. The only thing the current UI supports is 3-for-$1 style sales using pricemethod 2.

Do you get the sense this is a very common scenario? Does it need to be really user friendly, or could there be an "advanced" batch editor where a highly trained user can more-or-less manipulate the database fields directly? That would be easy enough to put together if these sales are rare enough that setup can be offloaded onto IT or scanning.

**Comment by joelbrock** [comment]
Well, this IS the first I'm encountering this issue, so my sense is that it is NOT a frequent occurrence.  The settings could definitely be exposed via an "advanced" batch editor GUI.  Or be handled directly via DB access.  
But, to clarify, in order to accomplish this NOW it would require editing the batchList schema and the SalesBatchTask to be aware of a specialgroupprice value, yes?

**Comment by gohanman** [comment]
Yes. Or if you just edited the special* fields in products directly and
didn't put it in a batch at all SalesBatchTask would not need any changes.
It would have to be turned off again manually, too, of course.

Adding a groupprice field to batchList does seem like a logical step
regardless. The current behavior is really a hack from way back when
adjusting table schemas caused major compatibility issues. If the editor
saves prices to both batchList.salePrice and batchList.groupprice and
SalesBatchTask falls back to salePrice when groupprice doesn't exist,
existing installs should behave identically but direct edits to the
database could enable the kind of sale you're describing.

**Comment by gohanman** [comment]
New column, backwards compatibility, and a new advanced editor.
6dc3d36d9d44af0883ff585ea0955d219f267db2

The "advanced" editor is very barebones. Dropdowns for the different price methods rather than having to know their numeric IDs would probably be a nice touch. Ditto sorting, item brand/description.

**Comment by gohanman** [comment]
2c26f638e31c5280be0cc2086fd3b5f469c031b5

Brand, description, & sorting.

**Comment by joelbrock** [comment]
Still having issues getting BOTH the sale price and the groupprice to cooperate with each other.
Current;ly, I have all the `opdata.products` fields populated in a manner that seems to make sense to me.  But when i ring the item, i get 5 rings at the special_price, and then the 6th and subsequent rings at 10% off the special_price, instead of 10% off the full set of matching items.  Which is a totally new and different behavior.

```sql
mysql> SELECT * FROM products where upc = 0089164100250\G
*************************** 1. row ***************************
                   upc: 0089164100250
           description: Merlot Cabernet
                 brand: Torre DI Spessa
        formatted_name: NULL
          normal_price: 8.99
           pricemethod: 6
            groupprice: 0.1
              quantity: 6
         special_price: 7.99
    specialpricemethod: 6
     specialgroupprice: 0.1
       specialquantity: 6
```

![screen shot 2015-07-20 at 10 33 32 am](https://cloud.githubusercontent.com/assets/52835/8782511/d3dd871e-2eca-11e5-85c1-0d70ef95f3ca.png)

**Comment by gohanman** [comment]
This is exactly what pricemethod 6 is supposed to do. When not on sale I would expect the 6th+ item to ring at $8.09. This has been the behavior since MoreThanQttyPM was created.

**Comment by gohanman** [comment]
Semi-related: b736532ca64eb159008af70290e81a13e5bc6942

I added some columns to the batchType table to properly correct some corners of functionality that were using hard-coded, WFC-specific batch type IDs. One of them is editorUI. There's already a secondary batch editing UI for setting up paired sales (that has popped up unexpectedly due to said hardcoding). The default UI really only works for assigning a single price to an item, IMO. The 2-for-$1 style pricing is shoehorned in but is awkward and confusing to deal with. There's at least a logical path going forward now to have purpose-built interfaces for different types of sales.

This doesn't resolve the question of what the desired behavior is here, of course.

**Comment by gohanman** [comment]
The batch editing issue here is resolved. How pricemethod 6 works or if a new price method is needed that can be a separate issue.

**Comment by joelbrock** [comment]
Sorry to pester about this, but this is still unresolved.  How would YOU do it?

The desired behavior is to have a 10% discount applied to all wine purchases of 6 or more bottles.  The discount applies to the first 6 and any subsequent wines rung.

I've tried a houseCoupon as well with no success:
![screen shot 2015-08-24 at 2 29 07 pm](https://cloud.githubusercontent.com/assets/52835/9453039/8b8f67f8-4a6c-11e5-96e2-fe4be633dd48.png)

**Comment by gohanman** [comment]
It could be a new price method entirely. Bottles 1-5 ring up at regular price, bottle 6 rings up at a weird adjustment price ($retail * 0.90 - (0.10 * 5 * $retail)), and then bottle 7+ rings up at 10% off.

Alternately it's a new minimum type for house coupons for a department minimum in quantity rather than $ amount. The coupon route might make more sense than a new pricing method - especially if it has to mix & match among bottles with different regular prices.

**Comment by gohanman** [comment]
New minimum type for coupon:
542d714109afbfcbb9e2057bf98d3e135b791a63

The coupon pictured above w/ new minType C (Department at least qty) instead of Q (Item at least qty) ought to works as expected.

**Comment by gohanman** [comment]
The minimum types C/C+ are officially in 1.8.0 but could probably be cherry-picked or manually copy/pasted into older versions fairly easily. Just requires adding the cases to the switch statement for minType.
