### ISSUE TITLE
core_op.memdefaults

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#532]
Not created on install.  Also, can't find the table creation commands in the code anywhere...

Also, 
```
Jul 16 19:37:54 ps245661 fannie[31024]: (debug) Undefined variable: FANNIE_TRANS_DB Line 239, fannie/install/InstallMembershipPage.php
Jul 16 19:37:54 ps245661 fannie[31024]: (debug) Undefined variable: FANNIE_TRANS_DB Line 243, fannie/install/InstallMembershipPage.php
Jul 16 19:37:54 ps245661 fannie[31024]: (debug) Undefined variable: FANNIE_TRANS_DB Line 247, fannie/install/InstallMembershipPage.php
Jul 16 19:37:54 ps245661 fannie[31024]: (debug) Undefined variable: FANNIE_TRANS_DB Line 252, fannie/install/InstallMembershipPage.php
Jul 16 19:37:54 ps245661 fannie[31024]: (debug) Undefined variable: FANNIE_TRANS_DB Line 256, fannie/install/InstallMembershipPage.php
```

**Comment by gohanman** [comment]
The table has been unnecessary since here (6e140b04921583dccc526ccb2afc45a9a8ff2c66) and stopped getting created on install here (286fe69fafdc2c1eee46fa6faed748fb8305c077). As of the latter commit table creation is all via the model classes. This was partially for easier testing and partially to stop maintaining dual definitions of each table.

The TRANS_DB error is a fairly ugly bug addressed 
* be923c1a7716f489461d4d4cc55aa7eef9e8a1d4 in 1.6
* 8660700fd7c6f9d15c1ca2d6527aae235cc9fd9f in 1.5
* 2d538e433b55c362a4a61b0b5f603cc1ee5cd430 in 1.4
* 18f65fa45114b08899dbe243f04efdcb8c63f31d in 1.3
* 170d6e32d37416567401f06397d56d4735d8ea4a in 1.2

**Comment by joelbrock** [comment]
rad!  thanks! 
So with a vanilla 1.6 install the Member Types editor doesnt allow me to create memtypes.  I tried manually adding entries to the memtypes table and those do not appear in the editor.

**Comment by gohanman** [comment]
db81a50bb2b43a8fd6449fa100d7fcd94d9f4073 (also patched back into the version branches). This probably merits a unit test. It's the kind of thing that rarely gets used and tested naturally post-install.

**Comment by gohanman** [comment]
And the unit test after refactoring the page: eb1dd20ab462a9729c47eab74e2a99b48a0b1911

I'm liking how FannieRESTful page lets me manipulate behavior to draw specific screens or fake form submissions.
