### ISSUE TITLE
Product Line Report form not loading

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#538]
visiting fannie/reports/ProductLine/ProductLineReport.php results in a page with no form.

**Comment by gohanman** [comment]
That's more or less as designed. It's not discoverable in the site map or list of reports (at least not upstream) since it doesn't have any user-facing entry form. When editing UPC/EAN items, then manufacturer digits of the UPC link the that report to show other products from the same manufacturer.
![product-line](https://cloud.githubusercontent.com/assets/426966/8943719/bbb3adc6-3541-11e5-962b-727b91b415f1.png)

I don't think there's any particular need to add a form and make this a standalone report since product list has essentially the same functionality. This variation only exists for the item editor integration as a quick reference to similar items.

**Comment by joelbrock** [comment]
ah ha!  great to know, thank you!  I did see the report listed in the All Reports page on the RVM install (v1.3-ish)

i do not see it on upstream installs.

**Comment by gohanman** [comment]
Looking at the history, it got excluded starting in 1.4. It's a one-line fix changing the $discoverable property to false if need be.
