### ISSUE TITLE
Printer Device Names under Ubuntu

### ISSUE THREAD

**Issue by gohanman** [CORE-POS/IS4C#556]
Posting for another store since it's not my normal environment. Say you've got a USB TM-H6000. There's no /dev/lp* device or a /dev/usb/lp* device. Where else might it show up? Is there any setup (modprobe etc) to control where it appears?

**Comment by joelbrock** [comment]
`/dev/usblp0` is another possibility.

Also usblp may need a jumpstart:
```bash
$ sudo rmmod usblp && sudo modprobe usblp
```

To ensure that the device is even getting picked up by the USB subsystem i generally do
```bash
$ dmesg | grep usb
```
to see all USB devices, give it an unplug and a re-plug to generate some `dmesg` output first.  then run the command.  The port / device you are fiddling with should be at the bottom.

Once the device is picked up i write a custom udev rule for it so that the device address doesn't inadvertently change (an issue ever since Ubuntu 12.04+):
Create the file `/etc/udev/rules.d/90-printer.rules`
Put this in the file:
```bash
SUBSYSTEMS=="usb", ATTRS{idVendor}=="04b8", ATTRS{idProduct}=="0202", SYMLINK+="printer0", MODE="0777"
```
Save and restart `usblp`:
```bash
$ sudo rmmod usblp && sudo modprobe usblp
```
Now, your EPSON TM-H6000 i/ii/iii/iv should always show up at `/dev/printer0' with wide open permissions (777).
