### ISSUE TITLE
Special Orders Rejuvenation

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#557]
For discussion.  Special Orders Interface bullet list of improvements needed/code enhancements.  Some of these are kinda far-out ideas, some more practical:
- This is one area that, while still totally functional, never got the bootstrap treatment.
- SPOs also need special pricing rules that are at least somewhat configurable.
- Tie SPO history to customer accounts in member mgmt.
- Track partial/pre-payments at register to SPO ticket in Fannie, and then *back* to the register fro final payment upon pickup
- Tie SPO statuses into the email notification system for automated alerts when orders are ready for pickup
- Report of items that a customer orders that will be on sale soon, for direct marketing purposes
- Alerts if item added to SPO ticket is currently in an upcoming sales batch
- Recurring orders?

**Comment by gohanman** [comment]
The bootstrap version actually exists in parallel (the CapitalizedPhpFiles in fannie/ordering). It's just so heavily used by so many people in my store that I'm hesitant to switch it on them. New installs should probably have menu entries point to the bootstrap'd version.

History's a one-liner to add a link. OldSpecialOrders.php?card_no=$mem and NewSpecialOrders.php?card_no=$mem both do exactly that. It's an artifact of WFC still useing the PIKiller plugin for member maintenance.

**Comment by gohanman** [comment]
I re-wrote (OrderViewPage::addUPC) to be less of a dense, spaghetti mess. I didn't add any configuration yet but just broke the pricing out into more discrete, understandable steps.

I see three basic pricing scenarios:
* Items the store does not carry
  * In this case, we **have** to work from vendorItems.
* Items the store does carry
  * In this case we're guaranteed to have a current retail price. An up-to-date cost and/or vendorItems record may or may not also be present.
* Items that are on sale
  * These should be items that the store carries and thus will have a current normal retail as well as the sale price.

So the configuration needs to define options for:
* How to calculate the price for an item that is not carried
  * Mark up from wholesale, possibly differing markups depending on member status
  * Mark down from retail if vendor catalogs include SRPs, again potentially differing based on member status
* How to calculate the price for an item that is carried
  * Mark up from wholesale, possibly differing markups depending on member status
  * Mark down from retail if vendor catalogs include SRPs, again potentially differing based on member status
* How to calculate the price if the item is currently on sale
  * Ignore sale pricing entirely
  * Use sale price instead of any other pricing mechanism.
  * Use the sale price only if it's better than standard pricing for stocked items.

I still think it will work best with the system's price calculation acting as sort of best guess. The result should still be human-editable.

A couple other general options I think we'll need:
* Default quantity as either cases or individual items. I think it will be easiest to manage if the system works more-or-less strictly in one or the other.
* Mark items (or realistically departments) that require an explicit quantity as well as a default quantity. This is to cope with items whose case size is ostensibly one but there's a minimum order.

I believe that covers most of what needs to be configurable. I see this piece as the logical starting point. Once the basic end-to-end process works (enter an order, estimate pricing correctly, print a SPO tag, scan tag through register & collect payment) we can look at additional reporting & alerting and so forth.

**Comment by joelbrock** [comment]
:+1: 
Really like the ability to set markups based on memTypes.  This sounds like a great start.

**Comment by gohanman** [comment]
18816e80452957975db1c6222bf2bde10f6741a2

Markup from cost & markdown from retail are both configurable per memType. Markdown is somewhat easier in that you only need to give a non-zero percentage to those who get a discount.

Mandatory quantity entry can be attached to departments. This is mostly used for wellness stuff where a "case" is one but there's a minimum order or cases can be split into smaller fractions. On further consideration I'm not sure it makes sense to have the default unit configurable as "cases" vs "singles". For the vast majority of product mixes, most items' minimum order will be a case.

**Comment by gohanman** [comment]
I updated the documentation to include info on current configuration options & pricing. https://github.com/CORE-POS/IS4C/wiki/Special-Orders

At this point it has some of the best test coverage of any part of the project. Which is not to say it's entirely free of bugs but most of the more stupid ones should be caught (also kind of cool if you've never looked at coverage reports):
https://codeclimate.com/github/CORE-POS/IS4C/coverage?page=21

**Comment by gohanman** [comment]
I don't think there's anything else to do with this until someone starts using it and can give feedback.
