### ISSUE TITLE
0000-00-00 or NULL dates not as 1969-12-31

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#561]
When the date in the database is either `0000-00-00 00:00:00` or `NULL` this, from `MemDates.php`:
```php
if (date('Y', strtotime($account['endDate'])) > 1900) {
            $account['endDate'] = date('Y-m-d', strtotime($account['endDate']));
        } else {
            $account['endDate'] = '';
        }
```
puts `1969-12-31` in the form.

I want it to be `''` in this case. The `1969-12-31` results from `strtotime()` failing.  Any of these tests gives the result I want:
```php
if (strtotime($account['endDate']) && date('Y', strtotime($account['endDate'])) > 1900) {
// or
if (date('Y', strtotime($account['endDate'])) > 1969) {
// or for that matter, which doesn't exclude say birthdates that might well be < 1969
if (date('Y', strtotime($account['endDate'])) {
```
Do you have a preference?

**Comment by gohanman** [comment]
After a little research, neither! This seems most correct:
```php
if (strtotime($date) !== false && substr($date,0,10) !== '0000-00-00')
```

The value returned for a 0000-00-00 date depends on the underlying architecture. On a 32-bit system, it returns false (which results in date 1969-12-31). On a 64-bit system, it returns a massively negative number (which results in date -0001-11-30). Other than this specific invalid value that MySQL uses, I think it makes sense to allow as wide a date range as the system integer can handle rather than setting a minimum.

**Comment by gohanman** [comment]
2c1d6ad2d69ff97a97ee2613c33d1c6e12cd017d

I figure it's easier to update the logic later if it's an API method.
