### ISSUE TITLE
Only One Discount Applies question

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#570]
I have Member Appreciation day set up as a HouseCoupon.
I have "Only one discount applies" turned "on" in the extras tab.

When ringing in the MAD coupon on a transaction with a member discount e.g. 10% staff disc. they both apply.

Depending on the houseCoupon discounttype the MAD discount either rolls into the member disc. (25%) or reports as a coupon on the receipt.

But essentially the "only one discount applies" switch isnt doing what I'd expect it to.  Guidance?  Suggestions?  I have images of receipts i can share if thats helpful.

**Comment by gohanman** [comment]
There was a bug with only-one-discount applies. A coupon with discount type "PD" should behave sensibly with this fix. 

There too many percentage-related discount types.
* %B should probably go away entirely. PD with non-stacking does the same thing
* OD seems pointless. I can't image using the coupon discount instead of the member's normal discount *even if the coupon discount is less* would be a common use case.
* %C should definitely go away. It was always weird and only exists to support a crazy (and thankfully departed) WFC discount
* % does not interact with the customer's discount at all (and thus always stacks in a sense). I'm OK with keeping this one as kind of "the simple one". It adds one line when the coupon's entered and that's it.
* %D can't interact with the customer's discount since it only applies to a subset of departments
* %E is insane IMO but if someone insists on micromanaging how subsets of the transaction are discounted it's an option.
