### ISSUE TITLE
Live Inventory

### ISSUE THREAD

**Issue by gohanman** [CORE-POS/IS4C#586]
Let's toss some plates in the air, shall we?

I'm looking at some small scale testing of something like perpetual inventory. The plan is to knock out something workable and then make refinements. Comments are welcome as there are more than a few moving pieces.

Let's start at a database level. I think there may only be two tables required to pull everything together.

### InventoryCache

Column | Purpose
---------- | ------------
upc | identify items
storeID | identify items (when needed)
cacheStart | datetime indicates oldest data included in the cache
cacheEnd | datetime indicates youngest data included in the cache
baseCount | the last physical count of inventory
ordered | number of items ordered during the cached period (in individual units)
sold | number of items sold during the cached period (in individual units)
shrunk | number of items shrunk during the cached period (in individual units)
onHand | baseCount + ordered - sold - shrunk

To unpack this a little bit:
* We're working in UPCs. Yes, there are edge cases where this is problematic. I think those items simply have to be excluded. The **sold** component cannot be measured any other way. Without that piece happening automatically any updates will by necessity include hand counting
* **baseCount** is what was in inventory at **cacheStart**, or as close to it as feasible. When bootstrapping the system it may need to include ordered quantities in transit if those orders are not in POS.
* The two datetimes offer different methods of determining a live count:
  * Sum all orders/sales/shrink that occurred after **cacheEnd**. I think this makes more sense when showing a live view inclusive of up-to-the-minute sales
  * Sum all orders/sales/shrink that occurred after **cacheStart**. I think this makes more sense when updating the InventoryCache table.
* I expect **sold** and **shrunk** to be updated nightly but **ordered** to be updated in real time.

The primary purpose of this, in my view, is to assist in ordering. I tell the system I have 10 widgets and I'd like to always have at least 5 on hand. When inventory drops below that threshold the system somehow starts shouting ORDER MOAR WIDGETS (emails, blink tags, whatever). But once I make the order I want the system to shut up again even though the items aren't physically present yet. What I plan to do is:
* When the order is placed, increment **ordered** - i.e., assume we will get what we ordered
* When the order is received, enter the actual quantity received and adjust **ordered** if needed.

### Creating Orders
I think the easiest approach here is to have the system create orders - whether automatically as a periodic process or on demand. That saves a bunch of data entry work even if there's no connectivity to press a button in POS and submit the order to the vendor. No matter how the order is actually placed the numbers need to get into POS. Having valid vendor catalogs would help (e.g., case size means it will generate more realistic quantities; costs mean better estimates; etc) but probably aren't strictly necessary.

### Receiving Orders
I'm hoping this will be a straight forward matter of confirming or adjusting quantities as needed. Checking the invoice cost against the order cost will depend heavily on how accurate vendor catalog info is but doesn't alter counts. I don't have an immediate solution in mind for mispicks although for items that aren't present in inventory at all I think they're safe to ignore.

### InventoryCounts

Name | Purpose
------- | ----------
inventoryCountID | generic meaningless primary key
upc | identifies items
storeID | identifies items (if necessary)
count | number of units present during this count
countDate | datetime the count was conducted
mostRecent | boolean 0 or 1 indicating this is the most recent count for this particular item
uid | user who entered the count
par | minimum number of units to keep in inventory

The idea here is that there may be a history of physical counts for an item but we only care about the most recent one. The whole system can be rebooted on a per-item basis by conducting and entering a physical count. The new count becomes **InventoryCache.baseCount** and the current datetime becomes **InventoryCache.cacheStart**. Any past orders/sales/shrink are now irrelevant for counting purposes. I think this will be very useful in getting the system dialed in initially as well as giving flexibility for ongoing audits.

It's also the launching point for the whole system. By default no items are tracked. To add an item to inventory the first thing you need to do is count it and establishing a starting value. I expect from an operational standpoint stores will typically start a trial run with one or two vendors to get a feel for how the whole cycle works before trying to scale it up.

### Misc
I'm looking at small vendors to start. I don't expect the underlying math or data to change with big vendors, but some of the workflows almost certainly will - especially in situations where "view the whole catalog at once" is a browser-crashing operation.

In hindsight I'm already unsure whether **par** really belongs in **InventoryCounts**. It's still early enough in development that altering schemas isn't a big deal, but if anyone else happens to be tinkering with their own tools on top of this be aware it's still a bit fluid.

Returns are entirely ignored. The assumption is they'll normally be shrunk. I'm sure this is not correct in all cases, but I think it's pretty far down the list of things that can contribute to skew.

I expect the most practical initial use case will be slow moving wellness items. You've got relatively few items to order at any given time so efficiency of the software tools is only moderately important, but going through dense sets to find those few items you need to order is troublesome. Honing the software and operational stuff (who-does-what-when) in this scenario should build to handling larger, more frequent orders.

**Comment by joelbrock** [comment]
:+1:

**Comment by flathat** [comment]
Very happy to see this.  I'll study-and-respond as soon as I'm over my immediate hurdle.

**Comment by chaploeb** [comment]
Interesting, and nice work.

Standard disclaimer from me:  I'm not currently a CORE or IS4C user, I'm an
interested bystander.  Slightly nonstandard disclaimer:  Weavers Way has
been building inventory management systems over the past year, with a very
different focus from this one, and the experience of doing that informs
many of these comments.  I hope this is at least somewhat helpful-- I'm
always a little unsure whether I should be weighing in on stuff like this
given my limited involvement with CORE.  Take this for what it's worth.

*UPC?*

Your focus on UPCs for tracking inventory seems somewhat dangerous to me
both in the context of ordering and in the context of inventory
management.  Given the potential for multiple UPCs to refer to different
units of the same product (case, each, sub-unit), I could see systems
giving the wrong answer pretty often on certain products.  I don't remember
how CORE handles this elsewhere so for the moment my ability to comment on
this decision is limited, other than to say it feels potentially
problematic.

*Why Do Perpetual Inventory?*

Your focus on demand fill ordering is interesting to me because it hasn't
been our primary goal in implementing inventory systems.  Perpetual
inventory and demand-fill ordering a separate, but related goals.  Other
reasons to do perpetual inventory include more accurate costing, tracking
inventory behavior by item (which can inform manual as well as demand-fill
ordering), publishing more accurate stock data to online shopping systems,
and tracking vendor behavior.  Additionally, there are many operational and
financial tracking benefits in situations where inventory items are moved
between locations-- this is our biggest focus right now.

In our particular system we use perpetual inventory for some of these other
reasons but NOT for demand-fill ordering (although we certainly haven't
ruled out the possibility of using it that way in the future).

*Demand Fill Ordering*

Despite the fact that we don't do demand-fill ordering, I have a few
thoughts about it from past experience and from examining our operations
here.

   - I think your instinct that demand-fill ordering is most useful in
   wellness is correct (we've looked at it also for grocery items stocked at
   our warehouse, although the definition of "demand" changes somewhat there).

   - One reason we haven't moved to demand fill ordering is that doing it
   in a way that makes appropriate decisions about vendor minimums and
   incentives gets really complicated really fast.  So, in wellness, we
   definitely order more from our main vitamin supplier at each transaction
   than a demand-fill system would typically have us do, but the cost savings
   of meeting their threshold are significant and make it worthwhile.  I've
   found that these kinds of constraints are way more common for us then
   they've been for me in previous environments where I've worked with these
   types of systems.  (Ultimately I'm hoping we can come up with a system that
   takes these kinds of issues into account, but the math gets more
   complicated quickly).

   - It's worth mentioning that past sales are (as you say) irrelevant to
   establishing inventory quantity after a physical count, they remain
   relevant to determining demand for demand-fill ordering; one system I
   worked with in the past went totally brain dead after every physical count.

*Inventory Management*

So, putting aside demand fill, for now and for us the focus of the
inventory system is on inventory management functions:  receiving,
transfers, vendor returns/credits and adjustments.  We also have "orders"
for inventory to move from one location to another (which are not orders
from a vendor).

I think your cache/count schema makes sense, although most systems I've
worked with simply call the Cache table "Inventory" and the other table
"Physical Counts" or something like that.  If you think of the schema that
way, it's clear that the "par" column and other columns like it (I suspect
in the long run you'll want more than one threshold-related column) belong
in the inventory table (one par per item per location; physical counts are
a historical record and there can and should be multiple records per
location).  It's generally understood that in most line of business
solutions I've used across the retail and mail-order industries that
inventory tables sometimes get out of whack and occasionally need to be
recalculated from counts and transactions.

If using the receiving system for costing, potentially there's a need to
identify some receiving transactions as having taken place BEFORE a count.
For example:  Inventory says we have 10 widgets.  We do a physical count
and find 15.  After recording the physical count, an invoice surfaces and
we discover the reason for the discrepancy is a delivery of 5 that came in
just before inventory and wasn't received.  Often we want to go ahead and
record that receiving in order to capture its cost data, but because of the
intervening physical count we want to make sure the count doesn't change.
 (The simple solution is to just have a date field on your receiving
transaction, and if the date of the receiving is before the last countDate
for the item received, you don't adjust the count.  I don't know/remember
how CORE handles costing, but there's more complexity if you need to figure
an average cost...)

David Chaplin-Loebell, IT Director
Office: (215) 843-2350 x127
Cell: (267) 971-4093


On Wed, Nov 4, 2015 at 9:36 PM, Eric Lee <notifications@github.com> wrote:

> Very happy to see this. I'll study-and-respond as soon as I'm over my
> immediate hurdle.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CORE-POS/IS4C/issues/586#issuecomment-153935071>.
>

-- 



Community-owned food markets open to everyone.
www.weaversway.coop

**Comment by gohanman** [comment]
First off, I definitely appreciate the input. What I'm doing here isn't exactly new territory so experience based on actually using such a system is invaluable.

### UPCs:
It seems to me that the transaction data is going to be in UPCs. Any alternative would have the cashier making additional selections after scanning an item. I think it's comparatively easier to make those decisions on the ordering side. Say I have two records in the PO with the same UPC. One's got SKU[1] 111 with 8 units/case and one's got SKU[1] 222 with 4 units/case. I can still sum that easily enough and figure out the average cost per unit.

I know this still fails in some situations. If I'm ordering cases of soda six packs and selling both six packs and singles the tracking is more complicated - and in different ways depending whether or not the singles and six pack share the same UPC. On balance I think I'd rather have the normal workflow be as simple as possible with extra layers of complexity for the edge cases. I expect there will always be some situations where it's more efficient to have a person simply count things rather than teach a person to understand multiple layers of nested and interconnected entities.

 [1]or item number or warehouse ID or whatever that particular vendor calls it

### Why Perpetual Inventory
My opinion here is definitely informed by the specific problems that led to operational folks buying into the idea. But from the standpoint of transitioning into perpetual inventory, focusing on demand-fill seems like the best place to start. The reality is the largest change and most of the additional work is going to fall on the people doing ordering and receiving. If the initial aim to make parts of *their* job easier it's better for morale in working through the change. "Do this extra work to make life easier for Finance and Scanning" is a weaker sales pitch.

### Demand-fill Ordering & Inventory Management
At the moment we're looking at human specified pars and human decisions when to actually place an order. A buyer would press some kind of "generate orders" button and then decide whether or not to move forward with those orders based on things like minimum orders. Or adjust quantities based on knowledge about upcoming sales. As an aside, telling people their decision making abilities are important and cannot be wholly replaced by a computer seems like another positive morale move.

The one reason that I put pars in with counts is that I **do** want the history (although it may wind up in a separate table). Setting pars automatically based on sales is already a tall task. I can imagine spending an enormous amount of time plotting sales trends with different variables (seasonality, special displays/end caps, depth of discount, type of signage, advertising, larger industry trends) and still guess wrong a whole lot. I'm curious if I can take a shortcut by looking at the history of human-assigned pars rather than the history of sales and have a more accurate basis for predictions. Maybe it won't prove useful but holding onto the history isn't terribly expensive.

I am planning to time-shift orders as they're received. Orders will go into inventory immediately based on the date they're placed, they'll shift forward based on the date received as well as correcting for actual received quantity. The use case I was thinking of was the reverse though. If I ordered 5 widgets yesterday and then count 10 of them today I need to re-date the order during receiving to maintain the "future" part of latest count + future orders/sales/shrink. But with a separate received date going backward should work too.

**Comment by gohanman** [comment]
Documentation, as it currently exists: https://github.com/CORE-POS/IS4C/wiki/Tracking-Inventory

I don't think this needs to hang around as a perpetual issue.The basic system is in place now. Future issues should be more narrowly focused on specific problems or uses.
