### ISSUE TITLE
How to do Ounces?

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#631]
My understanding is that most other co-ops using CORE-POS price their bulk herbs per pound — well, per hundredth of a pound. (Please correct me if I’m mistaken in this.)

At the moment George Street Co-op prices herbs per *tenth of an ounce*, and we have many entrenched customers who might be spooked by a sudden switch to pounds. Obviously, using ounces prevents using the connected Magellan pound scales.

I tried entering these items into the database with a per-ounce `price` and with both `scale` and `qttyEnforced` set to 1. It works great when I use the `2.3*2345` entry method.

When I enter just `2345` at the lane (forgetting to specify the weight), it forces me to enter one, which is great — but it interprets any input as being less than one whole unit and having 2 or 3 places of decimal precision. Unfortunately we often have more than an ounce, and more than a single decimal digit of precision is unfortunately impossible for us.

Is there any way to set the precision enforced under `qttyEnforced`, either per-item, per-department, or globally? Alternatively, is there a way to let the cashier specify the decimal explicitly in this dialog as well?

**Comment by gohanman** [comment]
We price bulk herbs per pound but weigh them separately with a thousandths scale. That dialog is expecting an entry between 001 and 999 (0.001 lb to 0.999 lb). The entry restrictions are both for simplicity and to minimize mistakes. A setting to allow entries w/ decimal included will probably be the easiest solution.

**Comment by scannerdarkly** [comment]
I agree, that might be best. Our current registers allow decimal@item entry, and this would minimize cashier errors during the time of transition.

**Comment by scannerdarkly** [comment]
Oh, @gohanman, do you have a preference between me writing the decimal entry code, or you? I’m okay either way, just want to make sure we don’t do redundant work.

**Comment by gohanman** [comment]
Go for it.

**Comment by gohanman** [comment]
Closing this for now. A pull request will create its own issue if/when someone implements this.

**Comment by scannerdarkly** [comment]
Implemented, including in the Office item editor. I wouldn’t be surprised if missed a thing or two somewhere, so feel free to send me back to the drawing board as necessary.
https://github.com/GeorgeStreetCoop/CORE-POS/commit/37ad1757070f3a62f7c015632bf655eb1d91fa21

**Comment by gohanman** [comment]
I would approach it more like fa10487c5a801f286f3745c457c57c97129e30fb.

I think implementing it as an extra product setting is confusing, error-prone, and creates unnecessary work. The scale setting does nothing unless `qttyEnforced` is also checked. And allowing some by-weight, manually keyed items to require one number format while other by-weight, manually keyed items use another number format will be a mess to keep track of for the cashier and item management. Making it a lane setting rather than an item settings ensures there's one and only one input format for this type of item. This would break down if someone wants to have multiple non-integrated scales with different input formats but I don't believe there's anyway to make that scenario not-confusing.

**Comment by scannerdarkly** [comment]
Good point! I’ll give this code a shot tonight or tomorrow. Thanks for finding a way to implement George Street Co-op’s needs into the codebase.

**Comment by scannerdarkly** [comment]
That works even better! Well, once a minor misspelling is corrected... https://github.com/CORE-POS/IS4C/commit/853a7126137b5e59f1e884ccd58d64749b2d7469

**Comment by gohanman** [comment]
Glad to hear it (downside of not running CI tests on non-master branches...)
