### ISSUE TITLE
Way to *keep* the receipt off?

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#639]
At our particular co-op we have a rather intense paper-saving culture. We generally print receipts only on customer request.

I’ve used the `RP` functionality mid-transaction to suppress receipt printing for that transaction, but the next transaction turns receipt printing back on again. Is there a setting to make it stay off? In other words, we’d basically only ever print receipts from the `RP` menu?

**Comment by gohanman** [comment]
No. There's a setting to turn receipts off entirely but then reprints won't work either.

**Comment by scannerdarkly** [comment]
Would it possible to make an intermediate setting, basically “don’t print but do allow reprint”?

**Comment by joelbrock** [comment]
I've addressed this in the past in one of 2 different ways:

1. program all tender keys with "NR" after the tendercode.  then use a shift-layer or other modifer key and have the shift layer input the straight tender code.
  - e.g. Cash button:  regular layer:  `CANR{ENTER}`, shft-layer: `CA{ENTER}`

2. drop `CoreLocal::set("receiptToggle",0);` into ini.php, alternatively, you could try and insert it into `opdata.parameters`  where param_key = 'receiptToggle' and param_key = 0

**Comment by scannerdarkly** [comment]
Trying @joelbrock’s approach #2. Looking good so far, thanks so much!

**Comment by gohanman** [comment]
77fcc95c7b52e8eaa656d7b28fde4f175b9327da

With that adjustment you could theoretically hook into the initial transaction state via plugin, e.g.
```php
class ReceiptOffPlugin extends Plugin
{
    public function plugin_transaction_reset()
    {
        CoreLocal::set('receiptToggle', 0);
    }
}
```

Main difference is the `RP` command could still turn the receipt back on mid-transaction.

**Comment by scannerdarkly** [comment]
That works great! [Here](https://github.com/GeorgeStreetCoop/CORE-POS/commit/7ab8a5d8a45cf5c39581e395bf5fd7cfc58bce64)’s that plugin, ever-so-slightly fleshed out.

**Comment by flathat** [comment]
At WEFC_Toronto about half of receipts are not wanted.  I've been asked to insert a dialog into all regular receipt printing that asks "Do you want to print this receipt?".

**Comment by gohanman** [comment]
You could possibly pull that off with a `PostParser` - to this point no one has used the API hook so I'm speculating a bit.

* PostParser runs after a command has been processed and somehow realizes the transaction has ended.
* PostParser redirects to another page for the Yes/No prompt
* Prompt page runs ajax-end.php (now AjaxEnd.php) either way with an appropriate toggleReceipt setting.
* Control returns to pos2.php.

The tricky piece is that when a tender finishes the transaction, `localtemptrans` is immediately rotated. There's no longer an existing transaction which puts some limits one what you can do. And you do want to still run ajax-end/AjaxEnd either way to kick the drawer, upload data to the server, and reset session variables for the next transaction.

You could write a `PreParser` that determines the current command will end the transaction and inserts a prompt, but I think that would be more difficult to get right for every different tender command and prompts the different tenders may throw.

**Comment by scannerdarkly** [comment]
I’m glad to see there’s interest in this topic, because at the moment (and maybe there’s something I’m missing), the plugin-based solution isn’t as efficient as I’d hoped. (My enthusiasm last night turns out to have been premature!)
1. When I want to print a customer’s receipt, I need to use the Reprint (`RP`) key, answer the “which receipt” dialog, and then repeat those two steps **again**. The first time through seems only to toggle the receipt mode; only on the second pass does it actually send the receipt to the printer.
2. Once I’ve done as described in #**1**, the system defaults to printing the receipt for the following transaction. Only after that does the receipt turn back off.

**Comment by gohanman** [comment]
I think that's the issue. It doesn't make any sense for the reprint page to obey the no-receipt setting. It was just never an issue without the plugin since it was [nearly] impossible to reach that page with the setting in that state.

**Comment by scannerdarkly** [comment]
I think https://github.com/CORE-POS/IS4C/commit/4be2322d439c116fc671a06b858e993caa235f7d touches the heart of the matter. I’ll give it a whirl.

**Comment by scannerdarkly** [comment]
This doesn’t seem to work. I disabled the `ReceiptOff` plugin, and deleted the `receiptToggle` hack in `office.parameters` too. And I tried a code edit...
```
        $saved = CoreLocal::get('receiptToggle');
        CoreLocal::set('receiptToggle', 1);
        $receipt = ReceiptLib::printReceipt('reprint', $trans);
        CoreLocal::set('receiptToggle', $saved);
```
...because I couldn’t see how this code would successfully enable printing unless it saved a change to the `receiptToggle` setting.

Is there something I’m misunderstanding about how all this should be configured?

Oh, also, if “Enable receipts” is off in `lane/install/receipt.php`, it seems to entirely disable the drawer kick, which I’m sure isn’t what your average user would want. I guess the kick message is sent through the same channel as the human-readable messages?

**Comment by gohanman** [comment]
Yours is right.

"Enable receipts" toggles on/off writing to the printer. Since the printer controls the drawer that's included. I could see calling it "Enable printer" although I'm not sure that's substantially more intuitive because the user still has to understand how those two components connect.

**Comment by scannerdarkly** [comment]
Okay, I’m not all that knowledgeable in this codebase, but I feel like maybe we’re dealing with code that’s being used for a few more purposes than its original design? Perhaps it would serve the user community best if we identified a new set of principles to realign it. Just a thought.

From what I’ve taken in at this point, it seems like various users want three discrete levels of overall printer activity:

1. None at all; don’t communicate with the port for any reason.
2. No printing, just drawer kicks and any other non-printing control actions.
3. Normal printing, drawer kicks, and any other non-printing control actions.

And it seems like for each major type of transaction (normal sale, cancelled sale, suspend, shrink, etc), users could want four discrete levels of print activity:

1. Print every time (subject to whether printing is turned off above).
2. Ask whether to print (subject to whether printing is turned off above).
3. Don’t print normally, but allow explicit reprint after the fact.
4. For this transaction type, don’t permit printing of any kind.

Such a two-level scheme might be considered to be over-engineering, but not by all that much, and I don’t think it would result in obscure or un-maintainable code. And if it’s too much, I believe just the second level of control (per transaction type) would cover my needs, and maybe the needs of others as well.

Just my 2¢! Thoughts?

**Comment by gohanman** [comment]
I don't think there are actually three different desires. The entire no-printer option is just a test/debug thing. PHP fails in catastrophic and unpreventable ways if it writes to a device file that isn't connected or ready. The setting's only there so new users (who may not even have hardware attached yet) can avoid certain catastrophes. I also don't think there's anyone who wants literally no printing. I haven't seen that expressed in this thread or ever heard someone request that. I think all we really have in production usage is people who want to print and kick drawers at various times.

Printing the end-of-transaction receipt is fundamentally tied into ending the transaction, getting ready for the next one, and shipping transaction data to the server. I'd have no objections to calling this a bad design with disparate tasks overly connected but it **is** the original design going all the way back to pre-CORE versions of IS4C. Refactoring the mess is a non-trivial undertaking to solve what frankly seems like a pretty minor problem. I believe prompting whether or not to print is the only one mentioned that *might* not be feasible and no one's actually tried implementing it.

Cancel, suspend, and shrink all have on-off settings and can all be reprinted. Print normally, with cashier override as needed, works. Don't print normally but allow reprint can be implemented at least two ways discussed in this thread. There may be a third way to do the same using changes mentioned in this thread.

Re-architecting an ugly section of code that handles several extremely important and fundamental aspects of the transaction because customizability is shy of infinite seems foolhardy.

**Comment by scannerdarkly** [comment]
Unfortunately “Don't print normally but allow reprint” isn’t actually implemented correctly by any recipe I’ve seen suggested thus far (unless there’s some permutation I’ve managed to miss in repeated attempts over the last three days). It’s on *this* basis, along with @flathat’s request, that I suggested some re-architecture. I’m not a fan of fixing what ain’t broke.

Again, if there’s some other way to get this to work, I’m open to keep trying. Conversely, if the only way to get this code to work for its more environmentalist users is to re-architect it, I’m open to giving that a go (once other aspects of our system have stabilized) and subjecting the code changes to as much thorough testing as anyone here desires.

**Comment by gohanman** [comment]
Can you expand on how the two different mechanisms Joel suggested that have both been used successfully in production environments don't cover what you're looking for? I haven't thoroughly tested the code changes suggested in this thread but having only two rather than three ways to solve a particular problem seems like a fairly academic problem.

**Comment by gohanman** [comment]
I did a bit of testing with 7bc9ae952631b3a37a91994794c2a7bda3239725, 4be2322d439c116fc671a06b858e993caa235f7d, and https://github.com/GeorgeStreetCoop/CORE-POS/commit/7ab8a5d8a45cf5c39581e395bf5fd7cfc58bce64. This is what I'm seeing:

* At initial log in, the receipt is off. When a transaction completes the receipt does not print.
* Pressing RP after the transaction does print immediately on the first use.
* After returning from the reprint screen to the main screen the receipt remains off. Ringing in another transaction does not cause a receipt to print.
* Pressing RP during a transaction does enable the receipt for that transaction. When the transaction completes the receipt returns to being off. The onscreen receipt icon does not update in this case though since there isn't a screen re-draw involved.

The cosmetic issue is probably fixable although I don't know are looking at the icon before or after pressing the RP key.
