### ISSUE TITLE
SimpleBackup simple fixes

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#646]
https://github.com/CORE-POS/IS4C/blob/master/fannie/modules/plugins2.0/SimpleBackup/SimpleBackupTask.php#L78
Here we are escaping the mysql password which breaks things if theres any special characters in the password by prepending a "\" to each special char.

https://github.com/CORE-POS/IS4C/blob/master/fannie/modules/plugins2.0/SimpleBackup/SimpleBackupTask.php#L81
And here we are referencing the mysqldump bin path for gzip instead of gzip.  Which on debian/ubuntu is "/bin/gzip"

This works for me, though might not be the best in terms of security and system variation
```php
            $cmd = realpath($FANNIE_PLUGIN_SETTINGS['SimpleBackupBinPath']."/mysqldump");
            if ($cmd === false) {
                $this->cronMsg('Could not locate mysqldump program', FannieLogger::ERROR);
                break; // no point in trying other databases
            }
            $cmd .= " -q --databases -h \"$FANNIE_SERVER\" -u \"$FANNIE_SERVER_USER\" -p\"$FANNIE_SERVER_PW\" \"$db\"";
            //$cmd = escapeshellcmd($cmd);  
            $outfile = $dir . '/' . $db . date('Ymd') . '.sql';

            //$gzip = realpath($FANNIE_PLUGIN_SETTINGS['SimpleBackupBinPath']."/mysqldump");
            $gzip = realpath("/bin/gzip");
            if ($FANNIE_PLUGIN_SETTINGS['SimpleBackupGZ'] == 1 && $gzip !== false) {
                $cmd .= ' | ' . escapeshellcmd($gzip);
                $outfile .= '.gz';
            }
```

**Comment by gohanman** [comment]
Well, obviously it'll break if the password contains a " character. It should probably have `escapeshellarg` on each piece rather than `escapeshellcmd` on the whole thing. 

As far as gzip, I have both /bin/gzip and /usr/bin/gzip (symlink) on a red hat-y system. It should probably just try both and give up if neither exists. That's not a fatal error anyway. The backup will still work but be bigger. On a lot of systems if push comes to shove there's probably more spare disk space than spare CPU cycles if the backups are getting into gigs in size (although the whole script probably works poorly at that point).
