### ISSUE TITLE
Tried pre-built NewMagellan driver on Linux

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#670]
This refers to the project at [CORE-POS/NewMagellan] (https://github.com/CORE-POS/NewMagellan)
NewMagellan version: 145564085
Linux: Ubuntu 12.04.05
`sudo mono pos.exe -v`
```
Unhandled Exception: System.TypeLoadException: 
Could not load type 'Magellan' from assembly 'pos, Version=0.0.0.0, Culture=neutral, 
  PublicKeyToken=null'.
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: 
Could not load type 'Magellan' from assembly 'pos, Version=0.0.0.0, Culture=neutral,
  PublicKeyToken=null'.
```

**Comment by gohanman** [comment]
What version of mono? That's the only thing I can think of.

The Main method of the application is attached to the Magellan class so this reads like it's crashing trying to find literally the first instruction in the application. If it's not executing any of the driver's code (because it can't find it) that can't really be fixed in the driver's code.

I know it gets farther than that - finding the entry point method and actually starting the application - under some 3.x versions of mono but don't have an exact number off hand.

**Comment by flathat** [comment]
```
wefc@lane1:~$ mono -V
Mono JIT compiler version 2.10.8.1 (Debian 2.10.8.1-1ubuntu2.2)
```
I'll see about upgrading and try it again.
