### ISSUE TITLE
Broken module finder

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#683]
At the moment I have at least three functions in Fannie: Reports > All Reports, Site Map and Install > Products > Module Manage that don't finish presumably because one or more mis-configured modules have crept in.  Nothing is logged to `debug_fannie.log`.

Is it at least theoretically possible to have a utility dedicated to finding the culprit(s), or at least the last member of a list that didn't fail?  If so I can try to write it; suggestions on approach welcome.

**Comment by gohanman** [comment]
Not really. The shutdown function ought to log parse errors as well as fatals (see commit) but I don't think it can do much other than write logs. With certain types of errors you simply cannot handle them gracefully and that's a limitation of the PHP language itself. I think it's literally impossible to have a sequence where 1) a fatal/parse/uncatchable error occurs and then 2) any notification appears on the browser screen. There's no way to send any additional info to the browser after one of these "hard crashing" errors.

The answer might differ slightly if we bump the minimum PHP version requirement to 7.0 but I think that would bring a whole different suite of headaches (probably more for admins than developers).

**Comment by gohanman** [comment]
Oh, you could try running one of the pages from the command line. It should be able to dump something to console where it crashes (you may need to tinker with the CLI php.ini or override some options (-d maybe?))

**Comment by gohanman** [comment]
I added a test script (39062829b7e20ce1bb2177a2656ad325e55f5f13). It's not standalone, unfortunately, since there are minor changes to FannieAPI. Normally `FannieAPI::listModules` locates all files that might contain relevant classes and then includes them to check if expected classes actually exist and whether they implement the base class it's looking for. The debug script short-circuits this so that `FannieAPI::listModules` just returns the list of candidate files and can print the name of each file before attempting to include it.
