### ISSUE TITLE
POS freeze; localtranstoday disappeared!

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#698]
Following a still-unexplained freeze of our POS lane, we are observing the following phenomena:
1. `localtranstoday` no longer exists on the lanes.
2. `dtransactions` remains empty on the office server.
What is the most efficient way to fix this? We’re running an only slightly modified fork of version 1.9.

**Comment by joelbrock** [comment]
simply calling up localhost/CORE/web/root/install on the lanes should re-generate any missing tables/views.

**Comment by scannerdarkly** [comment]
Tried that repeatedly; it doesn’t create `localtranstoday` unfortunately.

**Comment by scannerdarkly** [comment]
Don’t know if it’s relevant, but `php-errors.log` keeps adding lines saying:
`[19-Apr-2016 21:24:13 UTC] PHP Notice:  Undefined offset: 1 in /CORE-POS/pos/is4c-nf/lib/models/op/ParametersModel.php on line 75`

**Comment by scannerdarkly** [comment]
Oh, and it won’t log in anymore. :(

**Comment by scannerdarkly** [comment]
Those freezes seem correlated with an out-of-memory error.
`[19-Apr-2016 21:26:45 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 207011 bytes) in /CORE-POS/common/SQLManager.php on line 791`

**Comment by gohanman** [comment]
The "slightly modified" part makes it really hard to say. 

Based on the line # given and the fact that you mention `dtransactions` on the server is empty, I'd guess you've built up a giant enough backlog of transaction data that it's bombing out trying to deal with that much data. That's not fixable per se; you can increase your memory limit in php.ini or shuffle data around manually with MySQL tools. That doesn't really answer why this happened and why data wasn't getting sent to the server more regularly.

From v0.9.5 forward there's potentially an update that will drop `localtranstoday` if it's a view and recreate as a table but there's no mechanism to apply schema updates automatically. Otherwise I don't know of any way to make the table disappear. In either event a failure to create the table ought to display info on screen and in `queries.log`.

The parameters notice is probably irrelevant to this. It would mean you have a malformed keyed array value somewhere in the table (in mine `TenderMap` is the *only* parameters value using a keyed array and that's been ignored in favor of `tenders.TenderModule` if the `tenders` table is up to date since v1.3).

**Comment by scannerdarkly** [comment]
Okay, `localtranstoday` showed up again on the lane. I was running (and debugging the install scripts repeatedly, so I’m not sure when exactly it got recreated but we’re good there.

`office_trans`.`dtransactions` is still empty though. How do I repopulate it?

Probably related, `office_trans`.`dlog` has no records newer than 4/14/216. How do I repopulate that as well?

I wish there were a single dashboard-style script which reported the apparent health of all the data tables.

**Comment by gohanman** [comment]
If `dlog1 differs from `dtransactions`, then `dlog` clearly still isn't a view of `dtransactions`. The lanes should be copying data from `translog.dtransactions` to `office_trans.dtransactions` after each transactions. The freeze issue indicates this has been failing for a long time. This process makes every effort to cope with schema discrepancies between the two tables. The `queries.log` on the lane is the best option for finding details.

Detecting every possible unexpected, manual change users might make to the database is a bit of a tall task. The updates page primarily fills this task but is purposely less adamant about "fixing" differences. That's mostly rooted in long, long term efforts to stay compatible with other flavors of IS4C and cope with minor differences in table structure.

**Comment by scannerdarkly** [comment]
Very sorry, I meant `dlog_15` not `dlog`! `dlog` is empty, and is a view on `dtransactions`.

Meanwhile, `dlog_15` has nothing newer than Thursday 4/14/216, which I would imagine tells us when things started going haywire.

In version 1.9, what module does the `translog.dtransactions`→`office_trans.dtransactions` copy after each transaction?

Oh, and I do understand my expressed wish was maybe not realistic, given CORE’s need to accommodate such a wide range of travelers. :)

**Comment by gohanman** [comment]
The upload happens here: https://github.com/CORE-POS/IS4C/blob/version-1.9/pos/is4c-nf/lib/Database.php#L412-L455 

The relevant underlying method is here: https://github.com/CORE-POS/IS4C/blob/version-1.9/common/SQLManager.php#L761-L821

In these we're on pretty solid, hasn't-changed-in-a-long-time ground. In essence the lane is:
* Collecting all the records from `translog.dtransactions`
* Inserting those records into `office_trans.dtransactions`
* Trimming `translog.dtransactions` to be empty again. This only happens if the previous insert step succeeds.

In your case it sounds like the first step is now hard-crashing because the volume of data that's built up exceeds your configured memory limit for PHP. You could up the memory limit OR manually copy the data over to the server and manually clear (DELETE, not TRUNCATE) the lane's `translog.dtransactions`. If you have more than one lane you'll have to take care not to lose data. Blindly `mysqldump`ing onto `office_trans.dtransactions` is going to replace the content of that table rather than append to it so the manual route would likely involve creating some extra tables and copy steps to avoid ever drop & replacing `office_trans.dtransactions`.

Secondarily there's the question of **why** this giant backlog has built up. The simplest explanation is network connectivity from the lanes to the server was down, but if that hasn't been the case `queries.log` on the lane is the only thing that's going to have info about why the insert step is failing.

**Comment by scannerdarkly** [comment]
I got the `dtransactions` transfer to work, using the information @gohanman provided. Thanks so much!

There may be a way to speed up the `transfer()` method and avoid the out-of-memory error even in cases of big backlog like this one (which I guess must’ve been due to connectivity). If I get a tested, reliable code improvement in place in my fork, I’ll let y’all know.
