### ISSUE TITLE
Store-Specific Reports in All Reports?

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#717]
Can we make Store-Specific reports show up in the ALL REPORTS page?

**Comment by gohanman** [comment]
Not really. For auto-discovery to work, CORE needs to be able to include a file and determine what's in it. In turn this means files subject to auto-discovery need to comply with a number of conventions to ensure nothing bad happens if they're `include`ed at random times from various paths. The flip side of ignoring the `Store-Specific` directory is that code in there *doesn't* need to follow any rules and I think that's legitimately useful for new users, legacy functionality, or quick & dirty solutions.

For custom reports that *are* discoverable via ALL REPORTS, I think the best solution is to package them in a plugin instead. It's effectively an opt-in step that the code is going to be well-behaved and wants to integrate into the larger system.

**Comment by joelbrock** [comment]
hey!  that's super helpful info.  Thanks @gohanman
