### ISSUE TITLE
Duplicate UPCs in batches break building batchMergeTable

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#776]
Duplicate UPCs in batches (`batchList`) cause a PRIMARY KEY error when `ReportDataCacheTask` tries to:
```MySQL
INSERT INTO batchMergeTable
                        SELECT b.startDate,b.endDate,p.upc,p.description,b.batchID
                        FROM batches AS b LEFT JOIN batchList AS l
                        ON b.batchID=l.batchID INNER JOIN products AS p
                        ON p.upc = l.upc
Duplicate entry '1908-0007153720101' for key 'PRIMARY'
```
The failure is logged to `fannie.log` and the error to `debug_fannie.log`.

Is there a place in batch management where duplicates could be removed or flagged? The one here was from a five year old batch; perhaps the feature already exists; simply displaying the batch did not draw attention to it and I used the batch editor to delete it. Fannie `1.6.0-2015.07.10`

If dups cannot be prevented the error does prevent a large part of the populating of `batchMergeTable` and so perhaps the error should have a higher priority than `WARNING`.

**Comment by gohanman** [comment]
The primary key thing was addressed here 33b0cadf15a23b67c12c98b44f855d5cac160528 (circa 2.0) although that's largely just to clean up log noise. The table itself hasn't been used for anything at all since much earlier 89a7032e96442b64e0730afae4eb80aece3b9914 (circa 1.3). The whole table should probably just be removed. 7d38061412a3e3d4c6b47bcefe3009d6bd4526ad

I don't think dropping primary keys is within the power of BasicModels so you may have to manually adjust it.

**Comment by flathat** [comment]
Is there ever a case where a upc could usefully be in a batch more than once?

**Comment by gohanman** [comment]
No.
