### ISSUE TITLE
Missing adodb-array.inc.php

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#779]
Suddenly the POS lane’s login screen says:
`Missing file: /CORE-POS/common/adodb5/drivers/adodb-array.inc.php
ADONewConnection: Unable to load database driver ''`

...and we can’t log in or use the lane. Any ideas what would cause this? There is no file `adodb-array.inc.php` anywhere on the system.

1.9 variant as always.

**Comment by gohanman** [comment]
Sounds like perhaps one of your driver settings has been changed to "array" instead of mysql/mysqli/pdo_mysql.

**Comment by scannerdarkly** [comment]
That’s it. In the lane’s `ini.php` table, `DBMS` had become `Array`. I have no idea how this happened.

**Comment by scannerdarkly** [comment]
It just set itself back. Ugh.

**Comment by scannerdarkly** [comment]
It turns out `lane/install/index.php` is rewriting `ini.php` with `$CORE_LOCAL->set('DBMS','Array', True);`, each time it’s loaded. *sigh*

**Comment by gohanman** [comment]
I don't have much advice besides "upgrade". It's not behavior that's present any more nor do I see anything in the commit history that sounds like it addresses this.

**Comment by scannerdarkly** [comment]
Is upgrading a simple process? I’m nervous about changing things further when I don’t understand what’s wrong already...

**Comment by gohanman** [comment]
Upgrades are documented here: https://github.com/CORE-POS/IS4C/wiki/Git-Practices#upgrades

It's functionally impossible for upstream to predict what kind of merge conflicts you'll run into without knowing what changes you've made in your own repo. Generally speaking I think this project's handling of out-of-date downstream questions is pretty generous compared to many but at some point it doesn't make sense to hunt through everything fixed in the last 7+ months trying to find a particular solution (and repeat that process ad nauseum for each subsequent issue).

**Comment by scannerdarkly** [comment]
I assume it’s best to backup the directories and data, shut down all communications between the machines, upgrade them all at once (as described in the above link), and then start them all back up?

**Comment by gohanman** [comment]
Not really.

Backing up data is fine as a routine best practice but upgrades won't automatically alter any tables.

Backing up directories is a borderline bad idea. If you need to undo the process you should be reverting via git as documented. "Restoring" files or folders from your backup instead is just going to make your repo's history a mess.

Communication between machines running different versions generally works fine. There's not any particular requirement to upgrade all machines at once and it's certainly unnecessary to disable any communication since that all happens between databases and upgrading code won't touch the databases.

I'd add the 2.1 is probably an easier merge for a first attempt since you don't have to deal with lane files moving around and directories being renamed to make all paths namespace-compatible.
