### ISSUE TITLE
$this->last_connection_error / $this->last_connect_error

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#780]
In multiple places in `SQLManager.php`, the code refers to both `$this->last_connection_error` and `$this->last_connect_error`. Surely only one of these forms is correct!

**Comment by gohanman** [comment]
Not backporting because I'm convinced there's any practical difference beyond code tidiness. The variable gets initialized to `false` regardless; whether it gets reinitialized correctly *after* a connection attempt fails is probably irrelevant. There's not a real scenario where repeated attempts would have different results.

**Comment by scannerdarkly** [comment]
Sure thing, thanks.
