### ISSUE TITLE
Loss of CoreLocal?

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#793]
Cashiers report one lane starting, in mid-transaction, to ask for password after every command and it not being possible to complete the transaction because of this. In one case closing the browser and re-opening on the transaction made it possible to complete the transaction.  In one instance the item after which the password-prompting started had `emp_no =0` and `trans_no =0` (but had the correct `register_no`) suggesting it might have lost `CoreLocal` for those. After completing the transaction the cashier reported that the password-prompting happened again but I didn't see `emp_no =0` and `trans_no =0` in any record for that transaction.

`transarchive` showed five other records, all `trans_type = C` or `L`, with `emp_no =0` and `trans_no =0`, all on this same lane.

This has been reported twice, yesterday and the day before, same lane, one that is relatively little used; I'm more certain of the exact transaction involved in the one from yesterday.

CORE roughly 1.9. Firefox under Lubuntu 14.04, has been installed for some months, but the reports of the issue are only recent (`transarchive` items notwithstanding). My other, more heavily used lane where there have been no reports of this is CORE 1.6, Firefox, Ubuntu 12.04.

Any idea what might cause this?

**Comment by gohanman** [comment]
It sounds as if the entire `$_SESSION` is disappearing. The locking behavior after each command would be triggered by https://github.com/CORE-POS/IS4C/blob/version-1.9/pos/is4c-nf/gui-modules/pos2.php#L234 if `timeout` is no longer set. The timeout quirk is effectively fixed in 2.0 but there are still going to be piles of problems if the session backing `CoreLocal` vanishes.

Do you have any privacy related browser plugins or settings that might interfere with session cookies? If there any redirect within your code where the domain name might change, such as from `localhost` to `127.0.0.1` or to a named virtual host?

**Comment by gohanman** [comment]
I went to address this and it's mostly fixed already. `AutoLoader::dispatch` checks to see if the session is valid (and even specifically if the cashier number is known) before drawing a page. If the session isn't valid it redirects to the sign in page to rebuild the whole session and have the cashier login again. Not every page uses that method but in [precisely] 1.9+ both `pos2.php` and `login3.php` do. Input parsing should probably do a similar check to detect this kind of problem more quickly.

**Comment by flathat** [comment]
I haven't had it happen again.
