### ISSUE TITLE
Non-Master SuperDepts in VendorPricingBatchPage

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#805]
I am trying to encourage use of non-Master Super Departments, for example to get a more focused set of items than SuperDept "RETAIL" returns for a large vendor. `/fannie/batches/UNFI/VendorPricingBatchPage.php` only supports Master Super Departments.

The list of candidates for the batch seems to be created successfully with these changes:
 In   `get_view()` L#312, to populate the `<SELECT>`

``` php
        $prep = $dbc->prepare("SELECT superID,super_name
            FROM superDeptNames
            WHERE superID > 0
            ORDER BY super_name");
```

and in the search
in `get_id_view()` L#183

``` php
        if ($superID != 99){
            $query .= " LEFT JOIN superdepts AS m
                ON p.department=m.dept_ID ";
        }
```

**Comment by gohanman** [comment]
I'd be opposed to this in general because I think it degrades usability. The common use case for this tool is immediately following a mass update to the vendor catalog's costs. Restricting the choices to `MasterSuperDepts` means if you check every entry in the list you're guaranteed to check every item. If the list is expanded to include alternate super departments (and the user doesn't have a perfect mental model of all the categorizations), it's easier to overlook items and/or waste time reviewing the same items repeatedly under different categories.

The specific notion of having a "RETAIL" super department is also problematic. The assumption that super department 0 is non-retail and everything else is retail is baked in really deeply lots of places. Many (most?) reports even include a built-in "All Retail" option. Maintaining a separate, manual category seems at best redundant and at worst confusing if the manual "RETAIL" option and built-in "All Retail" give different results.

Adding a built-in "All Retail" option to this particular tool would be sensible if that's the specific need ("All" right now is literally everything including non-retail). But having a local definition of retail vs non that differs from the built-in definition of retail vs non is going to cause weird inconsistencies. Making the built-in definition customizable isn't out of the question but it's a much bigger undertaking than a single page.
