### ISSUE TITLE
SuperDept maintenance

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#813]
Any reason for not support Deleting a SuperDept, perhaps requiring that it be de-populated first? SuperDepts that don't have any members do not appear in the list in `item/departments/SuperDeptEditor.php` but do in other place such as Advanced Search.

It would also be nice to be able to edit SuperDept Names.

I'm happy to take these on if there are no effects I'm not aware of.

**Comment by gohanman** [comment]
Deleting one shouldn't cause any immediate effects. I might lean towards adding a `disabled` or `deleted` column instead. The total volume of data in `superDeptNames` is always going to be relatively small so it doesn't cost much to the decision reversible. Making the user de-populate it first would prevent accidental deletions, but the user might not know all the possible ripple effects to different reports. Zero should probably be an exception that can't be disabled or removed entirely.

The largest effects would occur if `MasterSuperDepts` changes; although the same effects would occur from de-populating so that might be beyond the scope of the question. It'd probably be useful to have a way to identify departments that aren't linked to any super department.

**Comment by gohanman** [comment]
Implemented w/ `superDeptNames.deleted` flag. Delete button should dynamically enable and disable based on whether the currently selected super department is empty.
