### ISSUE TITLE
Labels on links to margin editors

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#817]
In `$ITEM/vendors/VendorIndexPage.php` in this code, which assigns part of the group of links under the Margin heading, and where `$num` is the number of `vendorDepartments` records the vendor has:

``` php
        if ($num == 0) {
            $ret .= "<a href=\"VendorDepartmentEditor.php?vid=$id\">This vendor's items are not yet arranged into subcategories</a>";
            $ret .= '<p />';
            $ret .= "<a href=\"VendorDepartmentUploadPage.php?vid=$id\">Upload Subcategory List</a>";
        } else {
            $ret .= "This vendor's items are divided into ";
            $ret .= $num." subcategories";
            $ret .= "<br />";
            $ret .= "<a href=\"VendorDepartmentEditor.php?vid=$id\">View or Edit vendor-specific margin(s)</a>";
            $ret .= "<br />";
            $ret .= "<a href=\"VendorMarginsPage.php?id=$id\">And Even More Margins</a>";
            $ret .= '<p />';
            $ret .= "<a href=\"VendorDepartmentUploadPage.php?vid=$id\">Upload Subcategory List</a>";
        }
```
- I don't understand why the display of the "And Even More Margins" link to `VendorMarginsPage.php` is dependent on there being `vendorDepartments`.
- The link labeled "View or Edit vendor-specific margin(s)" goes to the editor for `vendorDepartments`. I would think a label like "View or Edit vendor subcategory margins" is more accurate.
- The table `VendorSpecificMargins` is edited by the link labeled "And Even More Margins". To me "View or Edit vendor-specific margin(s)" would be more appropriate.

The `HelpContent()` would also benefit from some explanation of `VendorSpecificMargins`.

The term "subcategory" implies a "category" above it, but there isn't one.  The term "category" might be used instead of "vendor department".  Personally, I prefer the latter as more specific to the situation, less open to misunderstanding.

**Comment by gohanman** [comment]
As far as I know "vendor department" no longer appears anywhere outside of the underlying code/SQL which is a much bigger headache. I don't particularly care what they're called in the UI so long as a) it isn't "department" and b) it's consistent. I personally do not read "subcategory" the same way and have real vendors that refer to their catalog sections as "subcategories" without having any "categories", but the reality is with basically zero standardization across vendors nothing we pick will line up with every vendor's terminology.

"And Even More Margins" is definitely a terrible label. It's not strictly dependent on `vendorDepartments` but I think it's easiest to explain as increasing layers of overrides from standard margins with increasing specificity.

**Comment by gohanman** [comment]
I built out the help text on margins a bit although a 2nd set of eyes would need to confirm if it makes any more sense than before. 

I think part of the naming convention problem here is that *both* sets of margins are vendor-specific. I do think the sequence of priority makes sense. If the vendor doesn't provide subcategories (or whatever term) itself then IMO you're better off using shipping or discount rate to make an across the board adjustment that's still tied to the default POS department margins. That way changes to the POS department margins will flow out to these kind of vendors automatically rather than having to go fix dozens of other entries.

If a vendor does provide subcategories, I think the single most useful reason to import them and attach margins is you can calculate pricing for items that aren't in `products` at all and don't yet have a POS department. It is an extra set of margins to maintain, but it streamlines new item entry a fair bit. It's also useful for some special order pricing schemes that need to figure out the "retail" price of an item the store doesn't normally sell.

I find that for the most part vendor-provided subcategories map pretty easily to POS departments - e.g., everything in vendor subcategory 2 would go into POS department 54. The last layer, "even more margins" / "vendor-specific POS department margins" are meant to deal with the occasional exception - e.g., something things in vendor subcategory 3 belong in POS department 74 but others should go in POS department 89. This is why the last layer is gated off when vendor subcategories don't exist. 

Admittedly, that's kind of me editorializing via the UI, but I don't think it's necessary or a good idea from a long-term maintenance standpoint to build up that level of layering across every vendor. Vendor subcategories tend to be self-limiting. Large vendors with well-formatted data usually have their own categorization. Small vendors with little or no good data rarely have that kind of detail. The former are the ones that are well-suited to an aggressively automated approach and so those are the ones that are worth delving into great detail on. But even on those type of catalogs I end up with some price rule'd (#806) and culled out of the automated system for manual, human pricing choices.
