### ISSUE TITLE
Permissions on Advanced Search > Group Edit

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#846]
When not logged in and doing an advanced search, I can still group edit and save changes to items. You cant change pricing, but you can edit departments, vendors and other properties.

**Comment by gohanman** [comment]
I ended up patching this into all versions back to 2.0 even though this isn't, strictly speaking, a bugfix because I was already adding a different fix to the same file (a12c93ea0bc208d2d8a6045f468b30a3b70691c3).

The other, more severe issue was that when editing 10 or fewer items, fields that *aren't* part of the group editor like `description` would get copied from the first item to all subsequent items.
