### ISSUE TITLE
Prevent over-discounting

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#848]
Question from a CORE-POS user that i could use some help a) understanding and b) answering:
> Does our system allow for a member to get cost plus and if an item is on sale will it give the best of the two prices.

>I believe our system works by discount, can be it done such that such items items on sale are not discounted at the same rate.  What I fear is that and item that goes on sale for 12% above cost is purchase by a business customer who has 20% sale price discount, then the customer is actually paying less than cost.

**Comment by gohanman** [comment]
What's the context here? SPO? Regular purchase?

It's probably preventable, automatically or by manually intervention, in an SPO where pricing is set beforehand. It's substantially more difficult with a `custdata` discount applied at time of purchase. At minimum it'd require overhauling everything related to calculating discounts and sales tax. I'm not sure it can be done without creating other headaches. It'd incur a bunch of cost tracking overhead in the common case - i.e., when a sale coincides with a promo price from the supplier. Those temporary cost changes aren't typically tracked at all but would have to be to pull this off.

It feels very much in the weeds - spending non-trivial labor chasing a random edge case.

**Comment by joelbrock** [comment]
My sense is regular purchases, and sales batches too perhaps.

It does seem like it should be incumbent on the staff (not the POS) to ensure pricing is done properly so as to prevent selling items for below cost.  Yet, at the same time, the POS does have the cost data, and a floor could be set at, say 5% above cost, below which the POS would just sell the item at the floor price.

This could be a method for safeguarding against human error causing a departments margin to erode b/c the buyer made a mistake, or something like that.  Pesky humans.

To be clear, this is NOT a request, just a question.

**Comment by gohanman** [comment]
POS **can** have the cost; it's never actually been required.

For regular pricing and sales batches, I think trying to do this kind of correction at checkout is a bad idea. I suspect in many jurisdictions you have to honor the advertised price. Even in places where auto-adjusting the price wouldn't be flat out illegal, any customer who noticed is going to be upset. It's fundamentally a backend problem to fix the price and adjust any signage on the sales floor.

The more technical objection here is inevitably someone's going to want an escape hatch. They'll want an actual loss leader, or they're discontinuing something and just want to get it out of inventory even if it is at a loss. So there'll end up being even more settings and places for human error and confusion.

For a customer account that has a transaction-wide discount, the scenario's a little different. If non-discountable items already exist and the customer isn't expecting that they'll always be able to add up their bill and have the discount exactly match a certain percentage, there's less of a customer service / messaging problem but there are still some technical hang-ups. Calculating the actual discount becomes more complicated which in turn makes calculating SNAP eligibility and sales tax more complicated.

Tracking promo costs would likely be mandatory. It's not uncommon for a sale cycle to have wholesale cost drop by 20% or more, and if cost in POS stays at regular wholesale this limit might get tripped incorrectly. If an item is on promo **and** the regular wholesale is changing there's a workflow problem unless we have two separate cost fields. Coincidentally, we do have two separate cost fields but it's not exposed in the UI. I'm not sure putting this in the UI even helps the basic problem since it's doubling the number of spots something might get entered incorrectly.

My hunch is if this discount related loss is happening a lot, the problem is the discount. Spending a bunch of time on the backend managing extra data to ensure the customer's 20% discount is actually less than 20% is not a solution. The fundamental problem is that the business cannot afford to give a 20% discount and the solution is to stop giving a 20% discount.

**Comment by joelbrock** [comment]
I am now thoroughly convinced.  THanks for thinking this through with me.
