### ISSUE TITLE
UPC at bottom left of 16UpP signs

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#868]
I don't know if it was intentional to remove the UPC from the bottom left of signs, e.g. 16Up but if not this will restore it, `fannie/classlib2.0/item/signage/Signage16UpP.php`
```php
    protected function drawItem($pdf, $item, $row, $column)
    {
         // ...
        /* Restore upc at bottom left of sign */
        if ($item['upc'] != '') {
            $pdf->SetXY($this->left-2 + ($this->width*$column),
                $this->top + ($this->height*$row) +
                ($this->height - $this->top - 7));
            $pdf->SetFont('GillBook', '', $this->SMALLEST_FONT);
            $pdf->Cell($effective_width, 6, $item['upc'], 0, 1, 'L');
        }

        return $pdf;
```
It is also absent from `12UpL` and `15UpL`.

**Comment by flathat** [comment]
Sorry, I see it is added to `12UpL` https://github.com/CORE-POS/IS4C/commit/cb5ea2461701f372d6725a111ee8834214fb2ee3 .

**Comment by gohanman** [comment]
Sorry, forgot to follow-up on this. The switch to using that space to list the regular retail price was intentional. It was seen as more useful information. The mass-produced signs these were modeled after simply couldn't provide that info because they didn't have store-specific retail pricing.

I don't necessarily love that 12-up solution but I don't want to get rid of the regular price or the sale dates. That doesn't leave a lot of options for where to fit everything. The 12-up breaks symmetry but I can't come up with any better placement.
