### ISSUE TITLE
Kitchen Ticket Printing

### ISSUE THREAD

**Issue by gohanman** [CORE-POS/IS4C#870]
This is a more restaurant-y feature, but conceptually the idea is to send a transaction or some subset of a transaction to a remote printer near the folks doing food prep.

### Configuration
Identifying which items should go to the prep printer could just be a table of (identifier, type). Using department numbers is going to be less work to maintain, but having a separate type column lets identifier include a mix of department numbers and UPCs.

To actually send the job the configuration should include a device filename and a `PrintHandler` selection. If the printer isn't connected to the lane directly or as a networked printer a custom `PrintHandler` implementation can handle the details of transmitting the text to the remote printer.

How, if at all, to interact with suspending transactions belongs in the configuration too.

### Implementation
The bulk of it could hook into `Plugin::plugin_transaction_reset`. It'd need to check the previous transaction for any items that need to be remote printed and then send them to the remote printer. Any comments in the transaction should probably be sent to the remote printer, too.

Resuming a suspended transaction [adds a log record](https://github.com/CORE-POS/IS4C/blob/master/pos/is4c-nf/gui-modules/suspendedlist.php#L218-L233) which could be used a divider to determine what was printed previously vs. what's new a still needs to be printed.

**Comment by gohanman** [comment]
### Doc
The remote print plugin sends designated items and all comments to a remote printer when a transaction is completed via tender or when a transaction is suspended. In the case of a resumed transaction only items and comments added after resuming will be sent.

### Config
Enable the RemotePrint plugin. You'll probably need to go over to the DB Updates tab to create the RemotePrint table. The RemotePrint table indicates which items will be sent to the remote printer. There is not currently a UI for this. Entries can include:
* UPCs: `identifier` is the UPC, `type` is `'UPC'`
* Department Numbers: `identifier` is the department number and `type` is `'Department'`

The plugin needs to be configured to specify **where** and **how** to print.

The first option is to have the remote printer device present directly on the lane, e.g. via network sharing or a very long cable. In this case Printer should be a device file such as `LPT2:` or `/dev/lp2' and the Driver should [probably] be `ESCPOSPrintHandler`.

The 2nd option is to attach a webserver to the remote printer and accept print requests over HTTP. In this case Printer should be a URL and Driver should be `RemotePrintHTTP`.

The remote webserver in the 2nd arrangement is not part of CORE. `RemotePrintHTTP` will POST a JSON object to the specified URL with properties `receipt` and `encoding`, e.g.
```json
{
  "receipt":"239502a80939d==",
  "encoding":"base64"
}
```

A simple implementation might look like:
```php
<?php

$request = json_decode(file_get_contents('php://input'), true);
if (isset($request['receipt']) && strlen($request['receipt']) > 0) {
  if ($request['encoding'] == 'base64') {
    $request['receipt'] = base64_decode($request['receipt']);
  }
  $fp = fopen('/dev/lp0', 'w');
  fwrite($fp, $request['receipt']);
  fclose($fp);
}
```

**Comment by otc-narendra** [comment]
It would be great to allow multiple remote printers, all printing the same thing. So some way for me to configure say two LPT ports that the print job is sent to.

**Comment by joelbrock** [comment]
Based on our field testing of this new feature i've got some feedback.
+ First off, fixing typos: 6db46418170a77ebfe381add73bd27e74a04e144
+ ReceiptLib::cutReciept is a private function, and the script failed on that call.  I edited ReceiptLib.php manually to make cutReciept `public` rather than `private` and that fixed it.
+ Now, with the DB table populated with 1 test department we are able to get the kitchen slips to spit out!  But the output appears to be duplicating itself.  Although the CM comment (no onions) does not duplicate so it's not _exactly_ a repeat.  see image below.
+ And lastly, upon SUSPEND, the remote slip continues to print out everything that matches the defined department.  Not just the items added since the last SUSPEND.  In the image below this slip was printed out on the 3rd suspend, after adding only 1 addt'l item to the transaction and then re-SUSPENDING .

![2017-07-11 12 53 50](https://user-images.githubusercontent.com/52835/28185999-667e0c5e-67ce-11e7-9d6f-b7fbb0a19741.jpg)


Addt'l notes:  EPSON TM-88v connected via ethernet to a Wifi AP in bridge mode.  THe Printer was assigned LPT1: via the EPSON Virtual Port assignment tool.

**Comment by gohanman** [comment]
f1e676868b8d8dbab77ddd2686dc1d11f98b124e

I see what's happening with suspend/resume. But the doubling is baffling. It looks to me as if the entire thing printed twice just w/o a newline after the first "no onions". Is that photo **after** dealing with the `cutReceipt` issue with just one real cut at the bottom of the photo?

**Comment by gohanman** [comment]
Scratch that. It's the way `cutReceipt` handles its argument that was doubling things.
af23a8705b489653ee6cb4f9f15e877d07e5d84c

**Comment by joelbrock** [comment]
FWIW:  While testing I tried changing `DORESUME` to `RESUME` with no change in behaviour.  Also removed the UPC test entirely so it was just looking for `charFlag == SR` and it still didnt work.

**Comment by otc-narendra** [comment]
Just tested the kitchen ticket printing. It's not printing twice any more, but I still get all the items printing, not just the ones after the previous resume. See attached photos of actual transaction and what printed.

- Narendra

________________________________

**Comment by otc-narendra** [comment]
Also, the receipt number on the remote print ticket is formatted as lane-cashier-transaction instead of the cashier-lane-transaction format normal receipts print. This could be confusing for staff...

- Narendra

**Comment by gohanman** [comment]
The transaction number piece is simple enough 252270db0b354695aba2582c199e43d0240e0434. Although the HRI from #884 would be shown instead once that feature is landed 9d2461d1fa77696c593d4a2e7184132a9dd06c95.

This might be the cause of the resumed items still printing 628244bc88fba30c1806bcaaddb4bf5aaed9eb27.

**Comment by otc-narendra** [comment]
Debug mode is always on (51fab89) did not fix it. However, once I comment out the code that checks for the debug flag, remote printing seems to work as expected at least in the case where the transaction is tendered. It correctly filters items based on the department specified in the RemotePrint table (I have not tested with individual UPCs or multiple departments). Also I cannot test the suspend/resume aspects because resume is hanging for me.

**Comment by gohanman** [comment]
The saved config value is probably still `No` instead of `0`. Re-saving plugin settings should fix it although frankly commenting that section it out is a perfectly sensible alternative. In the long run there's rarely if ever going to be a reason to enable that debug output anyway.

Where does resume hang for you? Shows a list of transactions and hangs when you choose to resume one, hangs before showing the list of resumable transactions, or somewhere else?

**Comment by otc-narendra** [comment]
Andy - resume is fine - see my edited comment above.

**Comment by otc-narendra** [comment]
RemotePrint table with UPC items does not seem to work. Department numbers work fine but when I add rows with type=UPC I don't see those items remote printed.

**Comment by gohanman** [comment]
RE: Multiple HRIs: print them each on a separate line? In original order? In reverse order?

I believe it's currently "last entry wins".

**Comment by otc-narendra** [comment]
Printing order is not a big deal from my point of view as long as it's consistent.

Do you think it's too confusing to have/allow multiple HRIs? I assume 'last entry wins' means that the last entry is what's used to Id the transaction for resume? Is the code currently enforcing uniqueness for HRIs or are you relying on the actual unique transaction Id under the hood and just showing the hri in the UI?

- Narendra

**Comment by otc-narendra** [comment]
We tried out these features (remote print and HRI based suspend/resume) yesterday in a production environment. Firstly, it all worked remarkably well so thank you all for your work on this! A special thanks to Eric for getting a last minute "hack" (his words!) in place to ensure that lane 1 suspend/cancel transactions printed properly.

Some comments/bug reports:

1) Typo in RemotePrint.php line 116 causing quantity of items to not print:
Current code:
                    . str_pad($line['quantity'], 5, ' ', STR_PAD_LEFT)`
Should say:
                    . str_pad($line['qty'], 5, ' ', STR_PAD_LEFT)

2) HRI(s) should print each time the remote ticket is printed (see comment thread above). I'm not clear from the discussion above how things would/should behave with multiple HRIs when it comes to identifying the transaction in the suspended transaction list. I'm willing to live with just one HRI per transaction - if the cashier enters a second HRI, it overwrites (or overrides) the first one. After all there is a semantic difference between an HRI and a comment even though the underlying implementation mechanisms might be similar.

3) Currently, comments and HRIs all print together at the bottom of the remote ticket. It would be far better if comments printed in the order they were entered. That way if I ring up a pizza and add a comment "no onions" it will show up right after the item rather than at the bottom where it becomes difficult to determine which line item the comment might be associated with. HRI(s) can print at the top or bottom of the transaction.

4) There was some odd behavior with regards to suspending/resuming transactions across lanes. Not entirely sure what the issues were and they could have been cashier error but I will research further and let you know if we uncover any bugs. As far as I know, we only "lost" one transaction and were able to re-enter it manually from the suspended receipt.

5) It would be nice to be able to add some sort of bitmap or text header to the remote receipt. Currently if the transaction contains a single item, it can be a tiny piece of paper that prints so it becomes difficult to manage and easy to lose. Also, any way to bump up the font size on the remote receipt? Kitchen staff seem to be far sighted?!!!

Thanks again for implementing this - it's going to be a great help to our operation.
