### ISSUE TITLE
Low inventory warning on lane [Question/Feature request]

### ISSUE THREAD

**Issue by otc-narendra** [CORE-POS/IS4C#887]
With our increasing use of CORE in a mixed grocery store/restauranty environment, we have run into an interesting issue related to “live” inventory that I’m hoping you can advise me on:
 
Let’s say that the kitchen has prepared ingredients for 50 pizzas. As customers come in and order pizza it is very difficult for the kitchen to communicate remaining inventory to the cashiers. In most restaurants the kitchen communicates limited inventory to wait staff who then limit additional orders but we make customers order at the counter and have no wait staff. Sales by item reports are not accurate because we are running open tickets (suspended transactions) and rings on suspended transactions do not show up in the reports. I suppose I could write a custom query to include these but I’m wondering if there’s an easy way to bring some of the inventory management functions into play here. How hard would it be for the lane to put up a warning message when inventory of an item goes below par value inclusive of rings on suspended transactions?

- Narendra Varma
Our Table Cooperative

**Comment by gohanman** [comment]
Perpetual inventory is going to have the exact same hang-up as sales reporting. Nothing on open tickets is going to actually "leave" inventory until the ticket gets closed out. It's somewhat possible to work around in either case; I'd lean toward having custom reporting that includes open tickets since there aren't nearly as many moving parts to keep track of.

My hunch is that a simpler solution would be best. Someone has to periodically enter that there's ingredients for 50 pizzas on hand and I strongly suspect these figures will drift out of accuracy a lot faster than packaged, shelf-stable grocery. There's inevitable loss in kitchen operations and tracking it in real-time would be quite difficult. If I was designing something for myself I'd probably start with a touchscreen terminal (or tablet) in or near the kitchen with a UI to tap into menu items and mark them "out" or "almost out" and then have that information reflected at the lane. 

The word that stands out to me is "communicate". Trying to make back-of-house to front-of-house communication faster and easier seems better than adding new data entry work and hoping the necessary communication occurs as a side-effect.
