### ISSUE TITLE
PO item search finding more than one adds them all to the order

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#893]
* Version of CORE? 1.8 + 2.7

* Issue with Office, Lane, or both? Office

* Is this [mostly] a bug report, feature request, or question? bug

In `EditOnePurchaseOrder.php` tab "Item Search" if the string matches more than one item it adds each of them to the order.  This happens before any choice is made from the dropdown that lists all the matches.

If this can't be replicated on a pure `2.7` installation then I'll wait until I've upgraded fully.

**Comment by gohanman** [comment]
First take at a solution for this is to retain the current behavior - i.e., add one to the order - only if the search returns exactly one item. Otherwise it simply presents the current quantity for all items that matched the search.

The divergent behavior is inevitably going to be a little confusing, but I think it's worthwhile to retain the functionality that you can add an item to an order simply by scanning a barcode and not require any further UI interactions.
