### ISSUE TITLE
Not SET innodb_lock_wait_timeout

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#925]
* Version of CORE? 2.7 upgrade

* Issue with Office, Lane, or both? Lane

* Is this [mostly] a bug report, feature request, or question? question

Re:
```
Failed Query on /IS4C/pos/is4c-nf/ajax/AjaxEnd.php
SET SESSION innodb_lock_wait_timeout = 5
Variable 'innodb_lock_wait_timeout' is a read only variable
```
Read-only on my antique MySQL 5.1.73. Can this be defeated safely? If so, what would be the best way to do it?  I don't see where `MysqlAdapter->setLockTimeout()` is being called.

**Comment by gohanman** [comment]
It gets called in `SQLManager::transfer()` to prevent the lane from hanging forever until triggering a fatal error because the server is online but is waiting on a lock to actually execute the query and return. There's not any straightforward way to defeat it.

If the logging isn't tolerable, I think the least bad option is an internal `SQLManager` method like `tryQuery` for queries that might fail but don't log anything.  A public API method like `setLockManagement($bool)` and a corresponding configuration option feels worse.

**Comment by flathat** [comment]
OK thank you.  In this particular server-lane situation the logging is tolerable and I won't worry about the rest. MySQL will eventually get upgraded to what the real lanes are running.
