### ISSUE TITLE
Class 'Monolog\Formatter\LineFormatter' not found

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#929]
* Version of CORE? Upgrading to 2.7

* Issue with Office, Lane, or both? Office

* Is this [mostly] a bug report, feature request, or question? Question.

I've copied `IS4C/*` from my development server to the production server and when I run Site Map on it get:
`fannie.ERROR: Class 'Monolog\Formatter\LineFormatter' not found Line 1362, File ...`
but don't get that error on the development server.  The `class` isn't referred to in the named file (a `FannieUploadPage` or any of the classes it extends.  I can work around the error by preventing `FannieLogger::factory()` from creating `new Monolog\Logger('fannie')`.

I'm wondering why the class isn't being found. `IS4C/vendor/monolog/monolog/src/Monolog/Formatter/LineFormatter.php` exists on the production server. `composer.lock` is the same on each server.  Possibly the difference  in version (`PHP5.4.39` vs `PHP5.3.3`) or configuration between the servers that will have other effects that I can't work around so easily?  Am I headed for a dead end?  `composer.lock` for `monolog` says: `"require": {"php": ">=5.3.0" ...`.

Per `composer.lock` 

+ `ramsey/uuid` `require`s `PHP5.4`. 
+ `symfony/event-dispatcher` and `symfony/yaml` `require` `PHP5.3.9`

How essential are those, esp. for `purchasing`? Downgrades possible that would run with `PHP5.3.3`?

`composer.lock` `require`s PHP versions higher than the development server has for several packages but the effects aren't show-stopping for the parts of `CORE` I'm using.

On the "old" production server there is no `composer.lock` and `composer.json` does not mention `symfony`.

I've scanned the [lock](https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file) page but it's a bit over my head at this point.

**Comment by gohanman** [comment]
That's mystifying. It only attempts to use monolog if `Monolog\Logger`. The fact that it's running at all means composer's autoloading must be working correctly for the `Monolog\*` namespace. I can't think of any explanation related to PHP versions where autoloading would work for `Monolog\Logger` but not for `Monlog\Formatter\LineFormatter`. Or really any explanation at all. The PHP version minimums usually mean the package uses syntax or functions that are only valid in the listed version or above. The autoloader function isn't doing any version checking or verification.

Nothing provided by composer is necessary in a one-store setup. UUID is used for creating payment URLs for `B2BInvoices`. I'm not entirely sure what the `symfony` bits relate to since those are coming in as dependencies of something else.

**Comment by flathat** [comment]
Thank you.
> Am I headed for a dead end?

At least this is not a certainty so I will continue the install later tonight.
