### ISSUE TITLE
Server-lane not responding to commands

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#930]
* Version of CORE? 2.7

* Issue with Office, Lane, or both? Lane

* Is this [mostly] a bug report, feature request, or question? Question

I've upgraded my production server using a copy of `IS4C/*` from a development server with a working server-lane.  The production server-lane had a session running which I neglected to close when I cut over to the different `IS4C/`.  It doesn't respond to any command: `SO`, `TL`, `300DP30000`, `MG`. No errors reported.  I've enabled "Show Page Changes" and "Show AJAX Errors", neither of which has displayed anything and "Log State Changes" which writes to `core_local.log`.  When it times out to lock it responds to a password.  I can put e.g. `productlist.php` in the address input and it displays the list. Upon choosing and item:
```
    COREPOS\pos\lib\gui\BasicCorePage::change_page()
    Line 100, /var/www/IS4C/pos/is4c-nf/gui-modules/productlist.php
        productlist::preprocess()
        Line 347, /var/www/IS4C/common/ui/CorePage.php
            COREPOS\common\ui\CorePage::drawPage()
            Line 85, /var/www/IS4C/pos/is4c-nf/lib/gui/BasicCorePage.php
                COREPOS\pos\lib\gui\BasicCorePage::__construct()
                Line 309, /var/www/IS4C/pos/is4c-nf/lib/AutoLoader.php
                    AutoLoader::dispatch()
                    Line 364, /var/www/IS4C/pos/is4c-nf/gui-modules/productlist.php
```
and a link: Follow redirect to `../gui-modules/pos2.php?reginput=0023932731080&repeat=1`
Clicking that gets:
`{"error":"Interface 'JsonSerializable' not found (\/var\/www\/IS4C\/pos\/is4c-nf\/parser\/ParseResult.php line 15)"}`
```
namespace COREPOS\pos\parser;
use COREPOS\pos\lib\ReceiptLib;
use \ArrayAccess;
use \Countable;
use \InvalidArgumentException;
use \Iterator;
use \LogicException;
use \Serializable;
use \JsonSerializable;
use \UnexpectedValueException;

class ParseResult implements ArrayAccess, Countable, Iterator, Serializable, JsonSerializable
{  // L#15
```
I don't know if that might just be from running the URL directly, but if I do the same thing on the development server from mid-session the response is normal, that is it puts the item in the transaction.

I don't know what sort of thing the JsonSerializable Interface is to know where to find it.

`localtemptrans`, `localtrans` and `dtransactions` are empty.  I'm curious where the information about cashier on the POS screen is coming from.  Perhaps if I can clear that, delete the "session", things will sort themselves.

**Comment by gohanman** [comment]
It looks like the root problem is likely PHP version. [JsonSerializable](http://php.net/manual/en/class.jsonserializable.php) is an interface provided by PHP >= 5.4.0.

Starting in CORE 2.3 input parsing operates on a `ParseResult` object instead of on a plain PHP `array`. The object implements all those interfaces so other code can still treat it as if it were an array. The purpose of this change is to prevent subtle bugs. With an array if you type `$ret['outpt']` instead of `$ret['output']` execution will continue but the resulting behavior will be wrong. The `ParseResult` object will instead throw an exception at the location of the mistake.

To make this work on 5.3 you'd need to remove the `JsonSerializable` interface reference and then account for it manually. I *think* you could put this into the end of `AjaxParser::ajax` just before returning:
```php
if (is_object($json)) {
  $json = $json->toArray();
}
```
Without the interface, `json_encode` can't work directly on the object so it'd have to be manually converted back to an array.

**Comment by flathat** [comment]
Thank you for the speedy reply.   I haven't been able to return to this until just now.

Removing `JasonSerializable` from the list of interfaces keeps this from failing, i.e. allows the item chosen from `productlist` to enter the transaction.  I don't know how to make that PHP-version-dependent so this is just hacked for my situation.
```PHP
// ParseResult.php
// ...
//use \JsonSerializable;
use \UnexpectedValueException;

//class ParseResult implements ArrayAccess, Countable, Iterator, Serializable, JsonSerializable
class ParseResult implements ArrayAccess, Countable, Iterator, Serializable
{
```
This allows handling of `TL`, `SO`, etc.
```PHP
// AjaxParser.php
    public function ajax()
    {
    // ...
        /*
         * Account for the absence of the JsonSerializable interface
         *  in the ParseResult object by returning a plain array.
         */
        if (is_object($json)) {
            $json = $json->toArray();
        }
        return $json;
    }
}
AjaxParser::run();
```
The server-lane is back in business.
