### ISSUE TITLE
Issues about Household Member editing

### ISSUE THREAD

**Issue by flathat** [CORE-POS/IS4C#938]
* Version of CORE? 2.6

* Issue with Office, Lane, or both? Office

* Is this [mostly] a bug report, feature request, or question? Bugs

+ On Adding a new Household Member `Customers.customerAccountID` `IS NULL` but is assigned the correct value if the member record is edited again.
+ Setting `FirstName` and `LastName` to `""` doesn't delete `Customers` records, but it does delete the `custdata` records.
    + A note about this deletion technique in the Help or in the module panel would be appreciated.
+ If Household Member name is same as Account holder, upon save the form field `Householdmembers_ID[] value=0`, for the same-name Household Member.  Upon the next Save the same-name HM is added again.  This HM cannot be deleted by setting then names to `""`.

**Comment by gohanman** [comment]
To unpack what's going on here a bit:

[Deleting Customers](https://github.com/CORE-POS/IS4C/blob/fa69eb3bac48038f22649d0477eee64b5a847432/fannie/classlib2.0/member/MemberREST.php#L572-L605) is handled differently. Rather than expecting will include IDs for all existing customer records it's instead going to delete any records that aren't included in the request. This should prune out any old records that were deleted from `custdata` previously.

[Linking customerIDs](https://github.com/CORE-POS/IS4C/blob/fa69eb3bac48038f22649d0477eee64b5a847432/fannie/classlib2.0/member/MemberREST.php#L291-L300) checks whether an ID has been assigned as well as whether the name matches. This deals with multiple users with the same first & last names.

The solution for customerAccountID is straightforward but the household member modules *also* have a change in handling blank names. Those modules now just pass along the data as submitted rather than trying to handle blank names directly.

**Comment by gohanman** [comment]
Included w/ 2.8
