### ISSUE TITLE
Transaction won't complete

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#946]
Starting last night, one of my lanes won’t actually complete a transaction. It shows a balance due of 0.37, even after repeated entries of that exact amount under different tenders.

Attempting to suspend the transaction results in a blank page. (URL lane/login.php)

CN requests a password, but pressing ENTER it just waits.

Going back to the main screen from either of those dead ends, we’re back at the transaction stuck at 0.37 due.

Scrolling through this stuck transaction, the final line of it is absolutely immense, seemingly consisting of every additional entry we’ve made since the trouble started. Here’s a screenshot: http://georgestreetcoop.com/downloads/2017-12-13_CorePosBug.png

The backend server doesn’t yet know about this transaction; it’s not showing up in reports.

My instinct is there’s some database field I need to clear out manually, but I have no idea which at this point.

* Version of CORE? 1.10-dev

* Issue with Office, Lane, or both? Lane

* Is this [mostly] a bug report, feature request, or question? Bug report

**Comment by gohanman** [comment]
That's certainly weird looking. If you can't tender out **or** cancel a transaction I'd guess your problem is in [finalizeTransaction](https://github.com/CORE-POS/IS4C/blob/version-1.10/pos/is4c-nf/lib/TransRecord.php#L800-L829). That function should, among other things, copy current transaction data (`translog.localtemptrans`) to longer-term storage before clearing the current transaction. The most obvious failure point would then be [here](https://github.com/CORE-POS/IS4C/blob/version-1.10/pos/is4c-nf/lib/Database.php#L787-L788). If copying the current transaction fails, the rest of the process halts so as to avoid throwing away any data.

I don't know **why** that particular query would fail although if logging is working correctly `queries.log` should have more info. Or you could try running the same query manually to see what the error is.

**Comment by scannerdarkly** [comment]
I started attempting to diagnose things using your pointers here, but rather quickly I discovered there was some sort of table corruption. By the time I realized this, I couldn’t even dump the transaction tables using mysqldump. Pressed for time, I tar’d the InnoDB table files, blew away the entire MySQL server, reinstalled from apt-get, and reset the configuration tables. I have my lane back, and I’ll investigate the missing 1.5 hours of transactions when I have a little more free time. :)

Thanks so much for getting back to me — I do intend to try to recover the missing transactions, and this guidance may still be the key!
