### ISSUE TITLE
Better handling of offline lanes

### ISSUE THREAD

**Issue by joelbrock** [CORE-POS/IS4C#947]
Make CORE-POS failover more gracefully in the event that one of the Lanes isnt currently online.

Presently this causes hangs and delays in product editing, syncing of all data, cron tasks, and more.

Or, create the option to designate a lane as a temporary / test/ or mobile lane in Fannie?  Which would only apply the looser syncing rules to those lanes and still expect all other lanes to be present and online at all times.

**Comment by gohanman** [comment]
Detecting the lane is offline is easy enough. The question would be what exactly to do next. When the lane detects the server is offline it stops trying to communicate until you sign out and back in. One issue would be what the equivalent action/trigger is to check again and see if the lane has come back online. Closing and re-opening the browser seems most logical. Another question would be whether the system itself will keep track of changes while the lane is unexpectedly offline and automatically send them when the lane comes back. If not there'd have to be some user facing notification while it's offline so the user knows that a products or membership sync is needed when the lane comes back. Although the worst case scenario isn't *that* bad since the overnight sync will kick in eventually.

I think it makes sense to separately have a way to manually mark a lane as offline (or not automatically synced) just to avoid continually checking for it and finding it offline over and over and over.

**Comment by otc-narendra** [comment]
At least to start, I think something simple would be sufficient. May I suggest: 
(a) A way to manually mark the lane as "not always online" on the fannie install page (or anywhere else in the server UI that makes more sense). 
(b) If a lane is marked as not always online, the server does not try and communicate with the lane and does not keep track of any changes that might have occurred while the lane was offline.
(c) When the lane comes back online, the user has to manually modify the setting in (a) above. When the setting is changed from offline to online, the server automatically performs a sync of products and membership, and/or perhaps, runs the overnight tasks against that lane? Alternatively, a single button to manually force the sync.

I would use this feature to save energy on my backup lane as well - instead of leaving it turned on 24x7, one could just fire it up when needed change a setting on fannie and voila.

**Comment by gohanman** [comment]
I purposely broke this up into a bunch of commits in case someone wants to backport. This is a barebones implementation that adds an `offline` flag to each lane. Most operations that would trigger a lane update - e.g., editing an item - will simply ignore lanes that have been marked as offline. The table sync page includes a checkbox to override this behavior and update the table on all lanes including those marked offline.

**Comment by flathat** [comment]
I'm happy to see this.  It will help with implementing a hot spare lane.

**Comment by gohanman** [comment]
I think this is all wrapped up?
