### ISSUE TITLE
Upgrades: Office first, or lanes first?

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#956]
When doing upgrades (which I assume you still recommend using the procedures outlined [here](https://github.com/CORE-POS/IS4C/wiki/Updating-CORE)), do you recommend doing the backend first, followed by the lanes? Or vice versa? Or does it not matter?

* Version of CORE?
All

* Issue with Office, Lane, or both?
Both

* Is this [mostly] a bug report, feature request, or question?
Question

**Comment by gohanman** [comment]
RE: Procedures: it depends what you're trying to do. The [Admin version](https://github.com/CORE-POS/IS4C/wiki/Updating-CORE) is oriented toward just managing a completely vanilla install. The update tool "dev" option will try to do a merge to preserve local edits but if that runs into problems (likely) you'll be better off with the [Developer version](https://github.com/CORE-POS/IS4C/wiki/Git-Practices). Your exact situation might be different but the general idea is to create a test branch to merge into so you can revert back to the old version if needed. Another option would be to install a vanilla newer version side-by-side with the existing version. You'd have to manually port any local changes/customizations across but depending on how many such changes there are it might be less work than going through a large merge.

It mostly shouldn't matter what order you upgrade things. Data transfers between the lane and server  compare table structures and only use whatever set of columns they have in common. Both will also check whether newer columns exist before trying to use them. Some features that rely on newer columns (or tables) won't work until schemas get upgraded but no existing functionality should break[1]. Personally I'd upgrade the backend first and lanes either as needed to support newer functionality or as time allows for testing. For me stability is usually a much greater concern on the lane side.

[1] I currently know of two incompatibilities related to schemas. The `products` table no longer contains an `advertised` column that pre-1.7 product searches reference [here](https://github.com/CORE-POS/IS4C/blob/version-1.7/pos/is4c-nf/lib/Search/Products/DefaultProductSearch.php#L56). The lane does not actually *use* this value for anything so simply deleting that lane fixes the problem. For side-by-side having 1.6 or 1.7 backend installed alongside a 1.8+ backend can cause problems in that the mere presence of newer tables will cause a behavior change rather than having an [explicit configuration toggle](https://github.com/CORE-POS/IS4C/commit/dda8f16adc8b58739edfd485044643920f35baec).

**Comment by scannerdarkly** [comment]
Thanks for this in-depth reply!

To make sure I understand completely: “For side-by-side having 1.6 or 1.7 backend installed alongside a 1.8+ backend can cause problems”. This refers to a situation where there’s a 1.6/1.7 installation and a 1.8+ installation, on different directories on the same server, but sharing the same database tables?

**Comment by gohanman** [comment]
Yes, precisely. I think that setup is a more realistic test of the new
version. There's usually a limit to how much patience people having poking
around in toy/fake data.

**Comment by scannerdarkly** [comment]
Thanks, I’ll start upgrading this weekend and see how it goes!
