### ISSUE TITLE
MySQL Strict Mode

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#964]
The latest versions of MySQL have Strict Mode enabled by default ([details here](http://www.percona.com/blog/2016/10/18/upgrading-to-mysql-5-7-beware-of-the-new-strict-mode/)).

Are the latest versions of CORE-POS tested to work with Strict Mode?

 

* Version of CORE?
all

* Issue with Office, Lane, or both?
both

* Is this [mostly] a bug report, feature request, or question?
question

**Comment by flathat** [comment]
In a recent upgrade the default for sql_mode was:
`ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`
with `STRICT_TRANS_TABLES` forcing a "strict mode" which implies the separate, deprecated `NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO`.

This disallowed use of what are called ZERO_DATES, that is dates of `0000-00-00 00:00:00` or "wildcard" month or day: `2107-00-00` or `2017-12-00` , which caused trouble.

Re: `ONLY_FULL_GROUP_BY`: Reject queries for which the select list, HAVING condition, or ORDER BY list refer to nonaggregated columns that are neither named in the GROUP BY clause nor are functionally dependent on (uniquely determined by) GROUP BY columns.

I removed those from `my.cnf` and restarted the service leaving these in effect: `NO_AUTO_CREATE_USER, NO_ENGINE_SUBSTITUTION` and there haven't been further problems.  I don't know that those two are beneficial in CORE.

**Comment by gohanman** [comment]
That's a good summary. I think all instances of zero dates are fixed as of v2.8. There are probably still improper GROUP BYs lurking here or there. Those should be treated as bugs when identified.

These are only backend issues. I'm not aware of any problems on the lane side relating to strict mode in MySQL 5.7. I would note that MySQL 5.7 *may* give user passwords an expiration date by default. There are a raft of problems that occur if the lane loses connectivity to its own database mid-transaction because the password expired.

**Comment by gohanman** [comment]
8011d695d3bcacd5d36198cd00b8934f084e5d1f

I changed the built-in tests to use a stricter SQL mode. Travis-CI's container environments are still running MySQL 5.6 but this should be a close approximation of running on 5.7. First test run turned up two bugs relating to strict mode (e10b11182b74068827318720b84fb6fdaf833e45 & c0857e1491c15e726cbfc27e78fb1042006d54df)

**Comment by gohanman** [comment]
Integration tests pass again. I lost track of the number of queries there were found and fixed. I'm not going to try and backport all the commits but the next release should be much closer to strict mode compatible.

I did run into some situations where `ONLY_FULL_GROUP_BY` gave spurious error messages, like
```sql
SELECT YEAR(tdate), MONTH(tdate), DAY(tdate)
FROM dlog
GROUP BY YEAR(tdate), MONTH(tdate), DAY(tdate)
```
would complain that `dtransactions.datetime` is not part of the group by clause. MySQL 5.7 is supposed to be better at functional dependencies but there might still be situations where you can't or shouldn't enable `ONLY_FULL_GROUP_BY` because the engine can't figure out that the query is deterministic or the engine generates unnecessary temporary tables (respectively).

**Comment by scannerdarkly** [comment]
Would all this imply that MySQL 5.7 is only really supported by CORE-POS version 2.8 (and later)?

**Comment by gohanman** [comment]
No, not really. The next release, 2.9, *might* work on MySQL 5.7 with default[1] SQL strictness settings; I can't say definitively without actually running it on 5.7 to see how much the query engine has improved over 5.6 in analyzing what GROUP BY clauses are legal. 2.8 and earlier (likely literally every release) could be made to work on MySQL 5.7 by configuring a compatible level of strictness. @flathat's configuration description is spot-on here.

[1] Since most people don't build MySQL from source "default" is probably a moving target, too. Different people delivering binary installs could deliver different default configurations, too.

**Comment by scannerdarkly** [comment]
That’s fair.

I had set `sql-mode = NO_ENGINE_SUBSTITUTION` in my.cnf, and that seems to be working fine so far.

Are there any times when `NO_AUTO_CREATE_USER` would make a difference with CORE-POS?

**Comment by gohanman** [comment]
No, CORE doesn't do anything to create or manipulate MySQL user accounts.
