### ISSUE TITLE
Dupes in bigArchive

### ISSUE THREAD

**Issue by scannerdarkly** [CORE-POS/IS4C#975]
I’m under the impression that bigArchive would be okay having a unique index like this:
`ALTER TABLE bigArchive ADD UNIQUE (datetime, store_id, register_no, emp_no, trans_no, trans_id);`
First off, am I wrong in this belief?

I attempted to create such an index and got flagged for having a duplicate record. Interestingly, it’s a `SIGNOUT` record, and both copies of it are field-for-field identical except for a different `pos_row_id` and `store_row_id`.

Can I afford to delete one instance of this record? (i.e. are `pos_row_id` and `store_row_id` referenced anywhere?)

* Version of CORE?
2.7

* Issue with Office, Lane, or both?
Office

* Is this [mostly] a bug report, feature request, or question?
Question

**Comment by gohanman** [comment]
There's really nothing that directly references `SIGNOUT` records. Adding a uniqueness constraint without knowing why it happened is a little dangerous since if it happens again transaction archiving will just fail completely. 

Your belief is generally correct, although logically it's more `date_id` than `datetime`. I tend to think this is not a good idea. This is effectively a distributed data store. I think you're better off being permissive in what you accept and monitoring for oddities than bringing everything to a halt if one client generates unexpected data.
