### ISSUE TITLE
NETePay version 5.07?

### ISSUE THREAD

**Issue by roberski** [CORE-POS/IS4C#982]
I noticed that as of the 31st of January Datacap has a update that supports EMV debit.
I was thinking about seeing if Vantiv would switch one of my deployments too it and start working on getting it going but I figured I would check in and see if there was already movement on this already.

* Version of CORE?
Ahh? Synced to Master

* Issue with Office, Lane, or both?
Lane

* Is this [mostly] a bug report, feature request, or question?
Question

**Comment by gohanman** [comment]
I haven't tried it; I don't know if anyone else has. I'm not sure you need anything switched or if you can just install the new NETePay and activate it with a deployment ID (which will deactivate whatever's currently using that ID).

There's an RBA version update that has to happen as well for the debit change to actually kick in. There's a tool to field-upgrade devices which I can pass along but probably can't link here. I can't speak to how reliable/safe that process is but I suppose worst case you have to send a device in to get the firmware reflashed.

**Comment by roberski** [comment]
I tried it says there is a version mismatch.
My spare is actually in getting re-encrpyted now and they said it also needed a RBA update.
I'm curious to see how it handles it so I'll probably talk to Vantiv when I get my extra back.

**Comment by gohanman** [comment]
Well I'd love to hear how that goes. It's not a pressing concern for me personally but it'd be nice to have more definitive answers than my wrong ones.

**Comment by gohanman** [comment]
I'm also running 5.07 now albeit in the Director setup and not with Vantiv. It definitely includes broader much broader support for chip debit transactions. I've actually been running dsiEMVUS v1.26 because if I upgrade to 1.27 (or, oddly, downgrade to 1.25) insert a chip debit card results in a prompt to choose US DEBIT or VISA CREDIT which is a very accurate description of what payment networks the card could use but also very confusing to normal people. In 1.26 chip debit cards auto-select US Debit and will revert to running as credit (if the card supports it) if you don't provide a PIN and just press green/enter.
